"""The agent registry table: an identity layer over an ``agent`` asset.

Phase 3 stores what an organization knows about an AI asset. Phase 4 stores *who*
one of those agents is: a stable identity that survives renames and version
changes, the category and version it was registered at, and a small set of runtime
facts. The relationship to the inventory is one-to-one and enforced here, not by
convention:

- ``agents.asset_id`` is **unique**, so an asset has at most one registry record —
  two records for one agent would be two identities for one thing;
- ``(organization_id, asset_id)`` references ``assets(organization_id, id)``, so a
  registry record cannot point at another organization's asset even if a handler
  forgot to check (the same composite-key technique Phase 3 uses for owners);
- the reference is ``ON DELETE CASCADE``: deleting the inventory record removes the
  identity with it, because an identity whose agent no longer exists in the
  inventory is an orphan, and orphaned identities are exactly what a registry must
  not accumulate.

Deliberately *not* duplicated here: display name, description, lifecycle status,
environment and owner. Those live on the asset, where Phase 3 already models them
with its own constraints — including the composite foreign key that makes a
cross-tenant owner unrepresentable. A second copy on this table would be a second
thing to keep in sync, and the registry's job is identity, not a shadow inventory.

``identity_id`` is generated by the database (``gen_random_uuid()``), never by the
application and never from anything a client sends. It is unique per organization
rather than globally: the tenant boundary is the security boundary in this system,
two organizations may legitimately hold the same identifier value without either
learning anything about the other, and per-tenant uniqueness is what a lookup
inside one tenant actually needs.
"""

from __future__ import annotations

import uuid
from typing import Any

from sqlalchemy import CheckConstraint, ForeignKeyConstraint, Index, String, UniqueConstraint, text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PostgreSQLUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from aicore_api.core.agents import (
    BUILD_REVISION_MAX_LENGTH,
    FRAMEWORK_MAX_LENGTH,
    VERSION_MAX_LENGTH,
    AgentCategory,
)
from aicore_api.db.base import (
    APP_SCHEMA,
    Base,
    TenantOwnedMixin,
    TimestampMixin,
    UUIDPrimaryKeyMixin,
)
from aicore_api.db.models.asset import Asset

TABLE_COMMENT = (
    "AI agent registry: the stable identity of one agent asset, with the category "
    "and version it was registered at. Tenant-owned; the referenced asset and the "
    "asset's owner membership must belong to the same organization, enforced by "
    "composite foreign keys."
)

_CATEGORY_MAX_LENGTH = 32


def _category_values() -> str:
    """Render the category vocabulary as the literal list a CHECK constraint wants."""
    return ", ".join(f"'{category.value}'" for category in AgentCategory)


#: Enum-ish column, ``VARCHAR`` + ``CHECK`` as everywhere else in this schema: a new
#: category stays an ordinary transactional migration, and PostgreSQL still refuses
#: a value the application does not know.
_CATEGORY_CHECK = f"category IN ({_category_values()})"


class Agent(UUIDPrimaryKeyMixin, TimestampMixin, TenantOwnedMixin, Base):
    """One registered agent."""

    __tablename__ = "agents"

    #: The stable identity of this agent, generated by the database. Never derived
    #: from the display name, never client-supplied, never changed: a rename or a
    #: version bump must leave it untouched, or "the same agent" stops meaning
    #: anything across the records a later phase will attach to it.
    identity_id: Mapped[uuid.UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        nullable=False,
        server_default=text("gen_random_uuid()"),
    )

    #: The inventory record this identity belongs to. Unique — one identity per
    #: asset — and tenant-checked together with ``organization_id``.
    asset_id: Mapped[uuid.UUID] = mapped_column(PostgreSQLUUID(as_uuid=True), nullable=False)

    category: Mapped[str] = mapped_column(String(_CATEGORY_MAX_LENGTH), nullable=False)

    #: The version the agent was registered at. A label, not a promise: the registry
    #: records what the organization ships ("1.2", "2024-07-18", "0.1.0-rc1" are all
    #: valid), because rejecting real versions would make the registry useless.
    version: Mapped[str] = mapped_column(String(VERSION_MAX_LENGTH), nullable=False)

    build_revision: Mapped[str | None] = mapped_column(
        String(BUILD_REVISION_MAX_LENGTH), nullable=True
    )
    framework: Mapped[str | None] = mapped_column(String(FRAMEWORK_MAX_LENGTH), nullable=True)

    #: Where the agent runs: runtime, region, instance. Validated against a closed
    #: model (``core/agents.py``) and refused if a key looks like a credential, so
    #: an identity record is always safe to read through the API.
    identity_metadata: Mapped[dict[str, Any] | None] = mapped_column(
        JSONB(none_as_null=True), nullable=True
    )

    #: The inventory record. Eagerly loaded because every read of an agent needs the
    #: asset's name, status and owner to answer with — and because the join is
    #: many-to-one, it cannot multiply rows or interact badly with ``LIMIT``.
    asset: Mapped[Asset] = relationship(lazy="joined")

    __table_args__ = (
        # The referenced asset and the owning membership are both addressed as
        # ``(organization_id, …)`` pairs, which PostgreSQL can only check against a
        # unique set of columns. ``uq_assets_organization_id_id`` is added by the
        # same migration, immediately before this table.
        ForeignKeyConstraint(
            ["organization_id", "asset_id"],
            [f"{APP_SCHEMA}.assets.organization_id", f"{APP_SCHEMA}.assets.id"],
            ondelete="CASCADE",
        ),
        # One identity per asset: an asset registered twice would be one agent with
        # two identities, which is the failure a registry exists to prevent.
        UniqueConstraint("asset_id"),
        # Identity is unique *within* an organization — see the module docstring.
        UniqueConstraint("organization_id", "identity_id"),
        CheckConstraint(_CATEGORY_CHECK, name="category_valid"),
        CheckConstraint(
            f"char_length(btrim(version)) BETWEEN 1 AND {VERSION_MAX_LENGTH}",
            name="version_length",
        ),
        CheckConstraint(
            "build_revision IS NULL OR char_length(btrim(build_revision)) "
            f"BETWEEN 1 AND {BUILD_REVISION_MAX_LENGTH}",
            name="build_revision_length",
        ),
        CheckConstraint(
            "framework IS NULL OR char_length(btrim(framework)) "
            f"BETWEEN 1 AND {FRAMEWORK_MAX_LENGTH}",
            name="framework_length",
        ),
        # Identity metadata is an object or nothing, for the same reason asset
        # metadata is: a JSON scalar in this column is a shape no reader can rely on.
        CheckConstraint(
            "identity_metadata IS NULL OR jsonb_typeof(identity_metadata) = 'object'",
            name="identity_metadata_is_object",
        ),
        # The listing's filters, tenant-first like every other index in this schema.
        Index("ix_agents_organization_id_category", "organization_id", "category"),
        {"comment": TABLE_COMMENT},
    )

    def __repr__(self) -> str:
        """Identify the row without quoting anything an agent's metadata holds."""
        return (
            f"<Agent id={self.id!s} identity_id={self.identity_id!s} "
            f"category={self.category!r} asset_id={self.asset_id!s}>"
        )
