"""The audit trail: one append-only row for every security-relevant thing that happened.

Phase 7's ledger answers "did this request already run?". This table answers a different
question, and the two must never be confused: *what happened in this organization, who
caused it, what was decided, and what came of it?* The ledger holds one row per
idempotency key and forgets refusals; the audit trail holds one row per event — including
the refusal — and has no key at all.

Four properties are enforced by the schema rather than promised by the code:

- **Append-only.** A trigger refuses ``UPDATE`` and ``DELETE`` (and ``TRUNCATE``), so an
  event cannot be rewritten or removed through the ORM, through raw SQL, or through a
  future maintenance script that forgot the rule. The only way past it is the session
  setting :func:`aicore_api.db.repositories.audit_events.audit_retention_override`, which
  exists for test teardown and is greppable.
- **Closed vocabularies.** Event types, actor types, resource types, decisions, outcomes
  and sources are all constrained to the values this build can produce, so a row that says
  something the application never says cannot be written. Widening one is a migration.
- **Attribution that cannot be partial.** A row that says a person did something must name
  both the person and the membership; a row that says a system did it must name nobody.
- **Metadata that stays a summary.** ``metadata`` is JSONB, constrained to an object and
  to a bounded size, and every value that reaches it passed
  :func:`aicore_api.core.audit.sanitize_metadata` — which is where secrets are redacted and
  where action arguments are deliberately absent (an execution records how many arguments
  the request carried, never what they were).

No foreign keys point out of this table except the tenant boundary. That is deliberate: an
event describes a resource that may since have been deleted, and a constraint would either
block that deletion or rewrite history when it happened. The identifier is kept as the fact
it was at the time — which is what makes a trail a trail.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from enum import StrEnum
from typing import Any

from sqlalchemy import CheckConstraint, DateTime, Index, SmallInteger, String, text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PostgreSQLUUID
from sqlalchemy.orm import Mapped, mapped_column

from aicore_api.core.actions import ACTION_ID_MAX_LENGTH
from aicore_api.core.audit import (
    AUDIT_SCHEMA_VERSION,
    ActorType,
    AuditDecision,
    AuditEventType,
    AuditOutcome,
    AuditResourceType,
    AuditSource,
)
from aicore_api.core.request_context import MAX_LENGTH as REQUEST_ID_MAX_LENGTH
from aicore_api.db.base import Base, TenantOwnedMixin, UUIDPrimaryKeyMixin

TABLE_COMMENT = (
    "Append-only audit trail: one row per security-relevant event in this "
    "organization, with server-resolved attribution, the decision and outcome the "
    "platform recorded, and metadata that holds summaries rather than payloads. Not "
    "an execution ledger and not an application log."
)

#: The largest metadata document the database will store. The application applies a
#: smaller bound (``core.audit.MAX_METADATA_BYTES``); this is the backstop for a row
#: written by a migration or a data fix rather than by the writer.
MAX_METADATA_BYTES = 8192

#: The same allow-list the request layer applies to a request id, expressed as a SQL
#: regular expression. A correlation identity that the application could not have
#: produced cannot arrive through any other path either.
REQUEST_ID_SQL_PATTERN = "^[A-Za-z0-9._:-]{1,64}$"

#: The action identifier shape used everywhere else in this build (Phase 7's
#: ``core.actions.ACTION_ID_PATTERN``): a dotted lowercase path, never a module name, a
#: function name or anything else that could be resolved into code.
ACTION_SQL_PATTERN = "^[a-z][a-z0-9_]*(\\.[a-z][a-z0-9_]*)*$"


def _value_list(values: type[StrEnum]) -> str:
    """Render an enum's values as the literal list a ``CHECK`` constraint expects.

    Derived from the code rather than typed out here, so a constraint cannot list a value
    the application does not know (or miss one it does) without a test noticing.
    """
    return ", ".join(f"'{value.value}'" for value in values)


class AuditEvent(UUIDPrimaryKeyMixin, TenantOwnedMixin, Base):
    """One thing that happened, in the organization it happened to.

    The identifier is generated by the database (as everywhere in this schema), the
    timestamp is the server's clock, and every attribution column is written from a value
    the server resolved — never from anything a client sent.
    """

    __tablename__ = "audit_events"

    #: What happened. One of :class:`~aicore_api.core.audit.AuditEventType`.
    event_type: Mapped[str] = mapped_column(String(64), nullable=False)

    #: The shape of the row. Pinned to what this build writes: a reader that does not
    #: understand the shape it is looking at should say so rather than guess.
    schema_version: Mapped[int] = mapped_column(
        SmallInteger, nullable=False, server_default=text(str(AUDIT_SCHEMA_VERSION))
    )

    #: When it happened, by the server's clock. Never a client-supplied time: a trail whose
    #: timeline a caller can choose is not a timeline.
    occurred_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )

    #: ``human`` or ``system``. See ``core.audit.ActorType``: the vocabulary holds exactly
    #: the origins this build has.
    actor_type: Mapped[str] = mapped_column(String(16), nullable=False)

    #: The authenticated person, when a person caused it.
    actor_id: Mapped[uuid.UUID | None] = mapped_column(PostgreSQLUUID(as_uuid=True), nullable=True)

    #: The membership that carried the role in this organization. Not derivable from the
    #: person alone (one person, many organizations), which is why it is recorded.
    actor_membership_id: Mapped[uuid.UUID | None] = mapped_column(
        PostgreSQLUUID(as_uuid=True), nullable=True
    )

    #: The agent an execution is attributed to, when the request named one. Attribution,
    #: never identity: the actor is still the authenticated person.
    agent_id: Mapped[uuid.UUID | None] = mapped_column(PostgreSQLUUID(as_uuid=True), nullable=True)

    #: The kind of row the event is about.
    resource_type: Mapped[str] = mapped_column(String(16), nullable=False)

    #: That row's identifier, as it was. No foreign key on purpose: the resource may be
    #: gone, and the event must still say what it was about.
    resource_id: Mapped[uuid.UUID | None] = mapped_column(
        PostgreSQLUUID(as_uuid=True), nullable=True
    )

    #: The operation: the registered action's identifier for an execution, or the
    #: ``resource.action`` permission that guarded the route for a lifecycle event.
    action: Mapped[str | None] = mapped_column(String(ACTION_ID_MAX_LENGTH), nullable=True)

    #: The decision recorded, in the vocabulary Phases 6 and 7 already use. ``NULL`` for an
    #: event that records no decision — a system operation answers to no authorization
    #: layer, and a request that has only been admitted has not been decided yet.
    decision: Mapped[str | None] = mapped_column(String(16), nullable=True)

    #: What became of it.
    outcome: Mapped[str] = mapped_column(String(16), nullable=False)

    #: Ties the events of one flow together. Server-established, from the request context
    #: the middleware set: a client may propose a request id, but a sanitized one, and it
    #: never decides attribution.
    correlation_id: Mapped[str] = mapped_column(String(REQUEST_ID_MAX_LENGTH), nullable=False)

    #: The originating HTTP request, when there was one. ``NULL`` for an internal path such
    #: as ingestion, which is exactly how "this was not a request" stays visible.
    request_id: Mapped[str | None] = mapped_column(String(REQUEST_ID_MAX_LENGTH), nullable=True)

    #: Where the event originated: the API, or the ingestion path.
    source: Mapped[str] = mapped_column(String(16), nullable=False)

    #: Structured, sanitized summary facts. Mapped to the column ``metadata`` (the
    #: attribute cannot be called that: ``metadata`` is SQLAlchemy's own registry, the same
    #: naming rule Phase 3 followed for ``assets.metadata``).
    event_metadata: Mapped[dict[str, Any]] = mapped_column(
        "metadata", JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )

    __table_args__ = (
        # The listing: this organization's events, newest first, with the identifier
        # breaking ties so a page cannot skip or repeat a row.
        Index(
            "ix_audit_events_organization_id_occurred_at_id",
            "organization_id",
            "occurred_at",
            "id",
        ),
        # "What refusals happened this week?" — the most common investigation, and the
        # one a security administrator opens first.
        Index(
            "ix_audit_events_organization_id_event_type_occurred_at",
            "organization_id",
            "event_type",
            "occurred_at",
        ),
        # "What did this person do?" — attribution is the second question asked.
        Index(
            "ix_audit_events_organization_id_actor_id_occurred_at",
            "organization_id",
            "actor_id",
            "occurred_at",
        ),
        # "Everything that happened in this request/flow" — the correlation join, which is
        # what turns a list of rows into a narrative.
        Index(
            "ix_audit_events_organization_id_correlation_id",
            "organization_id",
            "correlation_id",
        ),
        # "The history of this asset/agent/policy" — the question a resource page asks,
        # in a later phase, and the one an investigation asks today.
        Index(
            "ix_audit_events_organization_id_resource_type_resource_id",
            "organization_id",
            "resource_type",
            "resource_id",
        ),
        CheckConstraint(f"event_type IN ({_value_list(AuditEventType)})", name="event_type_valid"),
        CheckConstraint(f"schema_version = {AUDIT_SCHEMA_VERSION}", name="schema_version_valid"),
        CheckConstraint(f"actor_type IN ({_value_list(ActorType)})", name="actor_type_valid"),
        CheckConstraint(
            f"resource_type IN ({_value_list(AuditResourceType)})", name="resource_type_valid"
        ),
        CheckConstraint(
            f"decision IS NULL OR decision IN ({_value_list(AuditDecision)})",
            name="decision_valid",
        ),
        CheckConstraint(f"outcome IN ({_value_list(AuditOutcome)})", name="outcome_valid"),
        CheckConstraint(f"source IN ({_value_list(AuditSource)})", name="source_valid"),
        # Attribution cannot be partial: a human event names the person and the membership,
        # a system event names neither. Written as equalities between two states so a third
        # actor type added later fails this constraint rather than passing by default.
        CheckConstraint("(actor_type = 'human') = (actor_id IS NOT NULL)", name="actor_named"),
        CheckConstraint(
            "(actor_type = 'human') = (actor_membership_id IS NOT NULL)",
            name="actor_membership_named",
        ),
        # An API event came from a request; an internal event did not. This is what makes
        # the request id column meaningful rather than decorative.
        CheckConstraint(
            "(source = 'api') = (request_id IS NOT NULL)", name="source_request_consistent"
        ),
        # Only an admitted execution request is undecided. Every other event carries the
        # outcome of something that finished, so a "pending" row that is not a request — or
        # a request row that claims to have finished — cannot exist.
        CheckConstraint(
            "(outcome = 'pending') = (event_type = 'action.requested')",
            name="pending_consistent",
        ),
        CheckConstraint(f"action IS NULL OR action ~ '{ACTION_SQL_PATTERN}'", name="action_shape"),
        CheckConstraint(
            f"correlation_id ~ '{REQUEST_ID_SQL_PATTERN}'", name="correlation_id_shape"
        ),
        CheckConstraint(
            f"request_id IS NULL OR request_id ~ '{REQUEST_ID_SQL_PATTERN}'",
            name="request_id_shape",
        ),
        CheckConstraint("jsonb_typeof(metadata) = 'object'", name="metadata_is_object"),
        CheckConstraint(f"length(metadata::text) <= {MAX_METADATA_BYTES}", name="metadata_bounded"),
        {"comment": TABLE_COMMENT},
    )

    def __repr__(self) -> str:
        """Identify the row without rendering the metadata it holds."""
        return f"<AuditEvent {str(self.id)!s} type={self.event_type!r} outcome={self.outcome!r}>"
