"""Phase 4 over HTTP: registration, identity, lifecycle, authorization, isolation.

The registry's tests are written the way its callers use it — authenticated requests
against the real database — so every assertion here is about behaviour a client
actually gets:

- the response contract (exact fields, no credential ever appears);
- identity generated by the server, stable across renames and version changes, and
  impossible for a client to set;
- lifecycle moves recorded, impossible moves refused through the error envelope;
- authorization per operation, checked against the permission table for every role,
  and read structurally from the built application;
- tenant isolation: another organization's agent, identity, owner or tenant is never
  reachable, and never distinguishable from one that does not exist;
- the boundary of this phase: no endpoint executes, controls or contains an agent,
  and the agent permission namespace holds nothing that would claim to.

One fixture detail shapes the order of these tests: :func:`authenticate` attaches a
token to the *shared* test client, so a test that acts as somebody else switches
identity for the client it is holding. Scene-setting therefore happens first, as the
owner, and follow-up reads that must be the owner's switch the client back.
"""

from __future__ import annotations

import uuid
from typing import Any

import pytest
from fastapi import FastAPI
from fastapi.routing import APIRoute, iter_route_contexts
from fastapi.testclient import TestClient
from sqlalchemy import Engine

from agents_fixture import AGENT_CATEGORIES, AgentFactory, agents_path, identity_path
from aicore_api.core.permissions import ROLE_PERMISSIONS, Permission, RoleCode
from aicore_api.main import create_app
from assets_fixture import insert_asset_row
from identity_fixture import Identity, IdentityFactory, suspend_membership

#: Every field an agent response may contain. Asserted exactly, so a future field
#: (a credential, a runtime handle) cannot appear in the contract unnoticed.
AGENT_FIELDS = {
    "id",
    "organization_id",
    "identity_id",
    "asset_id",
    "display_name",
    "description",
    "category",
    "version",
    "framework",
    "build_revision",
    "status",
    "environment",
    "identity_metadata",
    "owner",
    "created_at",
    "updated_at",
}

#: The prefix every registry route shares.
_AGENT_PARENT = "/organizations/{organization_id}/agents"


def _agent_url(organization_id: uuid.UUID, agent_id: uuid.UUID | str) -> str:
    """The item URL for one registered agent."""
    return f"{agents_path(organization_id)}/{agent_id}"


# ── Registration ─────────────────────────────────────────────────────────────


def test_registering_an_agent_returns_its_identity(agents: AgentFactory) -> None:
    """The full contract, field by field, for a registration that names everything."""
    record = agents.register(
        display_name="Support Triage",
        category="customer_support",
        version="1.2.0",
        description="Answers tier-1 tickets.",
        status="active",
        environment="production",
        framework="langgraph",
        build_revision="a1b2c3d",
        identity_metadata={"runtime": "python3.11", "region": "ap-south-1"},
    )
    assert record is not None
    body = record.body
    assert set(body) == AGENT_FIELDS
    assert body["display_name"] == "Support Triage"
    assert body["category"] == "customer_support"
    assert body["version"] == "1.2.0"
    assert body["description"] == "Answers tier-1 tickets."
    assert body["status"] == "active"
    assert body["environment"] == "production"
    assert body["framework"] == "langgraph"
    assert body["build_revision"] == "a1b2c3d"
    assert body["identity_metadata"] == {"runtime": "python3.11", "region": "ap-south-1"}
    assert body["owner"] is None
    assert uuid.UUID(body["identity_id"]).version == 4
    assert body["asset_id"] != body["identity_id"]


def test_a_registration_may_state_only_what_it_needs(agents: AgentFactory) -> None:
    """Category and version are the minimum; everything else has a documented default."""
    record = agents.register(display_name="Minimal Agent", category="other", version="0.1")
    assert record is not None
    body = record.body
    assert body["status"] == "draft"
    assert body["environment"] == "unknown"
    assert body["description"] is None
    assert body["framework"] is None
    assert body["build_revision"] is None
    assert body["identity_metadata"] is None
    assert body["owner"] is None


@pytest.mark.parametrize("category", AGENT_CATEGORIES)
def test_every_category_can_be_registered(agents: AgentFactory, category: str) -> None:
    """The vocabulary is complete: every documented category is registrable and returned."""
    record = agents.register(display_name=f"{category} Agent", category=category, version="1.0")
    assert record is not None
    assert record.category == category
    assert record.body["category"] == category


@pytest.mark.parametrize(
    "payload",
    [
        {"category": "sentient"},
        {"category": ""},
        {"category": "AGENT"},
        {"version": ""},
        {"version": "   "},
        {"version": "v" * 65},
        {"status": "suspended"},
        {"status": "retired"},
        {"status": "archived"},
        {"environment": "everywhere"},
        {"identity_metadata": ["runtime"]},
        {"identity_metadata": {"api_key": "sk-live-whatever"}},
        {"identity_metadata": {"runtime": "python3.11", "notes": "not declared"}},
        {"identity_metadata": {"runtime": ""}},
        {"framework": "f" * 65},
        {"build_revision": "b" * 129},
        {"trust_level": "high"},
    ],
)
def test_a_registration_outside_the_contract_is_refused(
    agents: AgentFactory, payload: dict[str, Any]
) -> None:
    """Invented states, categories, labels and fields are 422s, not silent writes."""
    assert agents.register(display_name="Refused Agent", **payload, expected_status=422) is None


def test_a_client_cannot_choose_an_agents_identity(agents: AgentFactory) -> None:
    """Identity is not a request field, so it cannot be set, spoofed or replayed.

    ``identity_id``, ``asset_id``, ``organization_id`` and ``id`` are all refused as
    unknown fields: a client names the agent, it does not name its identity.
    """
    for reserved in (
        {"identity_id": str(uuid.uuid4())},
        {"asset_id": str(uuid.uuid4())},
        {"organization_id": str(uuid.uuid4())},
        {"id": str(uuid.uuid4())},
        {"agent_identity_id": str(uuid.uuid4())},
    ):
        assert (
            agents.register(display_name="Spoof Attempt", **reserved, expected_status=422) is None
        )


def test_the_display_name_is_not_the_identity(agents: AgentFactory) -> None:
    """Two agents with one name, and one agent renamed twice: identity never moves."""
    first = agents.register(display_name="Support Triage", version="1.0")
    second = agents.register(display_name="Support Triage", version="1.0")
    assert first is not None and second is not None
    assert first.identity_id != second.identity_id
    assert first.display_name == second.display_name

    identity_before = first.identity_id
    for name in ("Support Triage v2", "Support Triage (prod)", "Support Triage"):
        response = agents.client.patch(
            _agent_url(first.organization_id, first.id), json={"display_name": name}
        )
        assert response.status_code == 200, response.text
        assert response.json()["identity_id"] == str(identity_before)
        assert response.json()["display_name"] == name


def test_registering_the_same_external_identifier_twice_is_a_conflict(
    agents: AgentFactory,
) -> None:
    """The same external identifier is the same agent: the second attempt is a 409."""
    first = agents.register(display_name="Support Triage", external_identifier="triage-9")
    assert first is not None
    refused = agents.register(
        display_name="Support Triage", external_identifier="triage-9", expected_status=409
    )
    assert refused is None

    listing = agents.client.get(agents_path(first.organization_id)).json()
    assert len(listing["items"]) == 1


# ── Reads ────────────────────────────────────────────────────────────────────


def test_listing_returns_the_documented_page(agents: AgentFactory) -> None:
    """A page has its own shape: items, the window, and an opt-in total."""
    agents.register(display_name="One")
    agents.register(display_name="Two")
    response = agents.client.get(agents_path(agents.organization_id))
    assert response.status_code == 200
    body = response.json()
    assert set(body) == {"organization_id", "items", "limit", "offset", "count", "total"}
    assert body["organization_id"] == str(agents.organization_id)
    assert body["limit"] == 50
    assert body["offset"] == 0
    assert body["count"] == 2
    assert body["total"] is None
    assert all(set(item) == AGENT_FIELDS for item in body["items"])

    with_total = agents.client.get(
        agents_path(agents.organization_id), params={"total": "true"}
    ).json()
    assert with_total["total"] == 2


def test_reading_an_agent_by_id_and_by_identity_agrees(agents: AgentFactory) -> None:
    """The identity lookup is the same resource, reached by its stable name."""
    created = agents.register()
    assert created is not None
    by_id = agents.client.get(_agent_url(created.organization_id, created.id))
    by_identity = agents.client.get(identity_path(created.organization_id, created.identity_id))
    assert by_id.status_code == 200
    assert by_id.json() == by_identity.json()


def test_a_missing_agent_and_a_missing_identity_are_404(agents: AgentFactory) -> None:
    """Unknown identifiers answer with the same envelope every other 404 uses."""
    response = agents.client.get(_agent_url(agents.organization_id, uuid.uuid4()))
    assert response.status_code == 404
    assert response.json()["error"]["code"] == "not_found"
    assert response.json()["error"]["message"] == "Agent not found"

    identity_response = agents.client.get(identity_path(agents.organization_id, uuid.uuid4()))
    assert identity_response.status_code == 404
    assert identity_response.json()["error"]["message"] == "Agent identity not found"

    # A malformed identifier is a validation error, not a lookup that silently
    # matches nothing.
    assert agents.client.get(identity_path(agents.organization_id, "not-a-uuid")).status_code == 422


# ── Updates ──────────────────────────────────────────────────────────────────


def test_an_update_changes_only_what_it_names(agents: AgentFactory) -> None:
    """PATCH merges: absent fields are left alone, present fields are applied."""
    created = agents.register(
        display_name="Support Triage",
        version="1.0",
        framework="langgraph",
        description="First description",
    )
    assert created is not None
    response = agents.client.patch(
        _agent_url(created.organization_id, created.id),
        json={
            "display_name": "Support Triage (prod)",
            "version": "1.1.0",
            "category": "workflow",
            "environment": "production",
            "build_revision": "deadbeef",
            "identity_metadata": {"instance": "pod-3"},
        },
    )
    assert response.status_code == 200, response.text
    body = response.json()
    assert body["display_name"] == "Support Triage (prod)"
    assert body["version"] == "1.1.0"
    assert body["category"] == "workflow"
    assert body["environment"] == "production"
    assert body["build_revision"] == "deadbeef"
    assert body["identity_metadata"] == {"instance": "pod-3"}
    # Untouched: the framework and the description were not in the request.
    assert body["framework"] == "langgraph"
    assert body["description"] == "First description"
    assert body["identity_id"] == str(created.identity_id)
    assert body["asset_id"] == str(created.asset_id)


def test_a_null_clears_only_the_fields_that_may_be_cleared(agents: AgentFactory) -> None:
    """``null`` removes a value where that is meaningful, and is refused where it is not."""
    created = agents.register(
        display_name="Support Triage", framework="langgraph", description="Something"
    )
    assert created is not None
    url = _agent_url(created.organization_id, created.id)

    cleared = agents.client.patch(
        url, json={"framework": None, "description": None, "identity_metadata": None}
    )
    assert cleared.status_code == 200, cleared.text
    assert cleared.json()["framework"] is None
    assert cleared.json()["description"] is None
    assert cleared.json()["identity_metadata"] is None

    for meaningless in ({"display_name": None}, {"version": None}, {"category": None}):
        assert agents.client.patch(url, json=meaningless).status_code == 422
    assert agents.client.patch(url, json={}).status_code == 422


def test_the_lifecycle_moves_are_recorded_and_retirement_is_final(agents: AgentFactory) -> None:
    """The transition table, exercised through the API."""
    created = agents.register(status="active")
    assert created is not None
    url = _agent_url(created.organization_id, created.id)

    assert agents.client.patch(url, json={"status": "suspended"}).json()["status"] == "suspended"
    # A suspended agent is still a readable record: this is a registry state, not a
    # kill switch, and nothing in this build acts on it.
    assert agents.client.get(url).status_code == 200
    assert agents.client.patch(url, json={"status": "active"}).json()["status"] == "active"
    assert agents.client.patch(url, json={"status": "retired"}).json()["status"] == "retired"

    refused = agents.client.patch(url, json={"status": "active"})
    assert refused.status_code == 409
    assert refused.json()["error"]["code"] == "conflict"
    assert agents.client.get(url).json()["status"] == "retired"

    draft = agents.register(display_name="Draft Agent")
    assert draft is not None
    draft_url = _agent_url(draft.organization_id, draft.id)
    assert agents.client.patch(draft_url, json={"status": "suspended"}).status_code == 409
    assert agents.client.patch(draft_url, json={"status": "retired"}).status_code == 200


def test_an_update_refuses_metadata_that_is_not_an_identity_record(agents: AgentFactory) -> None:
    """The metadata contract holds on PATCH as well as on create."""
    created = agents.register()
    assert created is not None
    url = _agent_url(created.organization_id, created.id)
    for refused in (
        {"identity_metadata": {"token": "abc"}},
        {"identity_metadata": {"runtime": 7}},
        {"identity_metadata": "python3.11"},
    ):
        assert agents.client.patch(url, json=refused).status_code == 422


def test_an_owner_is_a_member_of_the_same_organization(
    agents: AgentFactory, owner_identity: Identity, identity_factory: IdentityFactory
) -> None:
    """An owner is resolved against this organization's active memberships."""
    created = agents.register()
    assert created is not None
    url = _agent_url(created.organization_id, created.id)

    owned = agents.client.patch(url, json={"owner_user_id": str(owner_identity.user_id)})
    assert owned.status_code == 200, owned.text
    owner = owned.json()["owner"]
    assert set(owner) == {"membership_id", "user_id", "email", "full_name"}
    assert owner["membership_id"] == str(owner_identity.membership_id)
    assert owner["user_id"] == str(owner_identity.user_id)
    assert owner["email"] == owner_identity.email
    assert owner["full_name"].strip()

    cleared = agents.client.patch(url, json={"owner_user_id": None})
    assert cleared.status_code == 200, cleared.text
    assert cleared.json()["owner"] is None

    outsider = identity_factory(role_code="owner")
    assert (
        agents.client.patch(url, json={"owner_user_id": str(outsider.user_id)}).status_code == 422
    )
    assert agents.client.patch(url, json={"owner_user_id": str(uuid.uuid4())}).status_code == 422


def test_a_suspended_member_cannot_be_given_an_agent(
    agents: AgentFactory,
    owner_identity: Identity,
    identity_factory: IdentityFactory,
    integration_engine: Engine,
) -> None:
    """Membership status is checked before ownership is granted, not after."""
    created = agents.register()
    assert created is not None
    member = identity_factory(role_code="viewer", organization_id=owner_identity.organization_id)
    suspend_membership(integration_engine, member)

    response = agents.client.patch(
        _agent_url(created.organization_id, created.id),
        json={"owner_user_id": str(member.user_id)},
    )
    assert response.status_code == 422
    assert "active member" in response.json()["error"]["message"]


# ── Deletion ─────────────────────────────────────────────────────────────────


def test_deleting_an_agent_removes_it_from_every_read(agents: AgentFactory) -> None:
    """A deleted identity is gone: by id, by identity, and from the listing."""
    created = agents.register()
    assert created is not None
    url = _agent_url(created.organization_id, created.id)

    assert agents.client.delete(url).status_code == 204
    assert agents.client.get(url).status_code == 404
    assert (
        agents.client.get(identity_path(created.organization_id, created.identity_id)).status_code
        == 404
    )
    listing = agents.client.get(agents_path(created.organization_id)).json()
    assert listing["items"] == []


def test_deleting_an_unknown_agent_is_a_404(agents: AgentFactory) -> None:
    """Nothing to delete is the same answer as nothing to read."""
    response = agents.client.delete(_agent_url(agents.organization_id, uuid.uuid4()))
    assert response.status_code == 404
    assert response.json()["error"]["message"] == "Agent not found"


# ── Authorization ────────────────────────────────────────────────────────────


@pytest.mark.parametrize("method", ["get", "post", "patch", "delete"])
def test_every_registry_operation_requires_credentials(agents: AgentFactory, method: str) -> None:
    """Without a credential there is nothing to authorize, so the answer is 401."""
    created = agents.register()
    assert created is not None
    anonymous = TestClient(agents.client.app, raise_server_exceptions=False)
    url = (
        agents_path(agents.organization_id)
        if method in {"get", "post"}
        else _agent_url(agents.organization_id, created.id)
    )
    response = anonymous.request(method.upper(), url, json={} if method == "patch" else None)
    assert response.status_code == 401
    assert response.headers["www-authenticate"] == "Bearer"


@pytest.mark.parametrize(
    ("role", "can_create", "can_update", "can_delete"),
    [
        (RoleCode.OWNER, True, True, True),
        (RoleCode.ADMIN, True, True, True),
        (RoleCode.AI_ADMIN, True, True, False),
        (RoleCode.SECURITY_ADMIN, False, True, False),
        (RoleCode.ANALYST, False, False, False),
        (RoleCode.VIEWER, False, False, False),
    ],
)
def test_the_four_registry_permissions_are_enforced_by_role(
    agents: AgentFactory,
    owner_identity: Identity,
    identity_factory: IdentityFactory,
    authenticate,
    role: RoleCode,
    can_create: bool,
    can_update: bool,
    can_delete: bool,
) -> None:
    """The permission table, verified through the API for every seeded role.

    Every role can read — that is what makes the split visible here: it is over
    *registering and changing* agents, not over seeing them.
    """
    # The target is registered by the owner, before the client becomes the actor
    # under test (the fixture's client carries one credential at a time).
    target = agents.register(display_name=f"Target for {role.value}")
    assert target is not None
    collection = agents_path(owner_identity.organization_id)
    item = _agent_url(owner_identity.organization_id, target.id)

    actor = identity_factory(role_code=role.value, organization_id=owner_identity.organization_id)
    client = authenticate(actor)

    assert client.get(collection).status_code == 200
    register = client.post(
        collection,
        json={"display_name": f"{role.value} agent", "category": "other", "version": "1.0"},
    )
    assert register.status_code == (201 if can_create else 403), register.text
    assert client.patch(item, json={"version": "1.0.1"}).status_code == (200 if can_update else 403)
    assert client.delete(item).status_code == (204 if can_delete else 403)


def test_a_refusal_names_the_permission_that_was_missing(
    agents: AgentFactory, owner_identity: Identity, identity_factory: IdentityFactory, authenticate
) -> None:
    """A 403 says what the caller lacks, and reveals nothing else."""
    viewer = identity_factory(role_code="viewer", organization_id=owner_identity.organization_id)
    response = authenticate(viewer).post(
        agents_path(owner_identity.organization_id),
        json={"display_name": "Denied", "category": "other", "version": "1.0"},
    )
    assert response.status_code == 403
    body = response.json()["error"]
    assert body["code"] == "forbidden"
    assert "agent.create" in body["message"]


def test_no_role_holds_permissions_the_registry_did_not_introduce() -> None:
    """The agent namespace holds exactly the four registry permissions.

    Stated as an assertion because the temptation to widen a role while adding a
    feature is exactly how a least-privilege table erodes — and because a permission
    for executing, suspending or containing an agent now would be a claim this build
    cannot honour.
    """
    assert {permission for permission in Permission if permission.value.startswith("agent.")} == {
        Permission.AGENT_READ,
        Permission.AGENT_CREATE,
        Permission.AGENT_UPDATE,
        Permission.AGENT_DELETE,
    }
    assert set(ROLE_PERMISSIONS) == set(RoleCode)
    for role, permissions in ROLE_PERMISSIONS.items():
        assert permissions <= set(Permission), role
        # Every role that may change an agent may also read it: a permission to move
        # something you cannot see would be an incoherent grant.
        if Permission.AGENT_UPDATE in permissions or Permission.AGENT_DELETE in permissions:
            assert Permission.AGENT_READ in permissions


def _required_permissions(route: APIRoute) -> set[Permission]:
    """Permissions a route declares, read from its dependency tree."""
    found: set[Permission] = set()
    pending = list(route.dependant.dependencies)
    while pending:
        dependency = pending.pop()
        permission = getattr(dependency.call, "required_permission", None)
        if permission is not None:
            found.add(permission)
        pending.extend(dependency.dependencies)
    return found


def _agent_routes(app: FastAPI) -> dict[tuple[str, str], set[Permission]]:
    declared: dict[tuple[str, str], set[Permission]] = {}
    # `app.routes` yields lazily-included routers; iter_route_contexts is how
    # FastAPI itself walks the effective routes.
    for context in iter_route_contexts(app.routes):
        route = context.original_route
        if not isinstance(route, APIRoute):
            continue
        # The registry's own routes: the collection and its items. Matched on path
        # *segments* rather than on the string "/agents", because a later phase's view can
        # legitimately contain that segment — /monitoring/agents measures the same subject
        # without being a registry route, and this test is about the registry.
        if route.path != _AGENT_PARENT and not route.path.startswith(f"{_AGENT_PARENT}/"):
            continue
        for method in route.methods - {"HEAD", "OPTIONS"}:
            declared[(method, route.path)] = _required_permissions(route)
    return declared


def test_every_registry_route_declares_the_permission_it_enforces() -> None:
    """Authorization is a property of the route, not of the handler body.

    Read from the built application rather than from the source: a route that
    forgets its requirement — or acquires the wrong one in a refactor — fails here.
    """
    assert _agent_routes(create_app()) == {
        ("GET", _AGENT_PARENT): {Permission.AGENT_READ},
        ("POST", _AGENT_PARENT): {Permission.AGENT_CREATE},
        ("GET", f"{_AGENT_PARENT}/identity/{{identity_id}}"): {Permission.AGENT_READ},
        ("GET", f"{_AGENT_PARENT}/{{agent_id}}"): {Permission.AGENT_READ},
        ("PATCH", f"{_AGENT_PARENT}/{{agent_id}}"): {Permission.AGENT_UPDATE},
        ("DELETE", f"{_AGENT_PARENT}/{{agent_id}}"): {Permission.AGENT_DELETE},
    }


# ── Tenant isolation ─────────────────────────────────────────────────────────


def test_another_organization_cannot_read_an_agent(
    agents: AgentFactory, identity_factory: IdentityFactory, authenticate
) -> None:
    """The id, the identity and the listing all answer "not here"."""
    created = agents.register(display_name="Private Agent")
    assert created is not None
    outsider = identity_factory(role_code="owner")
    client = authenticate(outsider)

    assert client.get(_agent_url(outsider.organization_id, created.id)).status_code == 404
    assert (
        client.get(identity_path(outsider.organization_id, created.identity_id)).status_code == 404
    )
    listing = client.get(agents_path(outsider.organization_id))
    assert listing.status_code == 200
    assert listing.json()["items"] == []
    assert listing.json()["count"] == 0


def test_another_organization_cannot_determine_whether_an_agent_exists(
    agents: AgentFactory, identity_factory: IdentityFactory, authenticate
) -> None:
    """A foreign id and an invented id produce the same status *and* the same body.

    That is what makes the 404 a non-disclosure rather than a hint: the difference
    between "yours, but not yours to see" and "does not exist" is not observable.
    """
    created = agents.register()
    assert created is not None
    outsider = identity_factory(role_code="owner")
    client = authenticate(outsider)
    tenant = outsider.organization_id

    foreign = client.get(_agent_url(tenant, created.id))
    invented = client.get(_agent_url(tenant, uuid.uuid4()))
    assert foreign.status_code == invented.status_code == 404
    assert foreign.json()["error"]["message"] == invented.json()["error"]["message"]

    foreign_identity = client.get(identity_path(tenant, created.identity_id))
    invented_identity = client.get(identity_path(tenant, uuid.uuid4()))
    assert foreign_identity.status_code == invented_identity.status_code == 404
    assert (
        foreign_identity.json()["error"]["message"] == invented_identity.json()["error"]["message"]
    )


def test_another_organization_cannot_update_or_delete_an_agent(
    agents: AgentFactory,
    owner_identity: Identity,
    identity_factory: IdentityFactory,
    authenticate,
) -> None:
    """IDOR on the write paths, and the record is checked afterwards as the owner."""
    created = agents.register(display_name="Untouchable", status="active")
    assert created is not None
    outsider = identity_factory(role_code="owner")
    client = authenticate(outsider)
    url = _agent_url(outsider.organization_id, created.id)

    assert client.patch(url, json={"display_name": "Renamed By Outsider"}).status_code == 404
    assert client.delete(url).status_code == 404

    authenticate(owner_identity)  # back to the tenant that owns the agent
    still_there = agents.client.get(_agent_url(created.organization_id, created.id)).json()
    assert still_there["display_name"] == "Untouchable"
    assert still_there["status"] == "active"


def test_a_caller_cannot_act_in_an_organization_it_does_not_belong_to(
    agents: AgentFactory, owner_identity: Identity, identity_factory: IdentityFactory, authenticate
) -> None:
    """The path names the tenant, and membership decides whether it is usable.

    The organization in the path must resolve against the caller's own memberships,
    so naming somebody else's tenant is not a way to reach their registry — the
    answer is the same 404 as for a tenant that does not exist.
    """
    created = agents.register()
    assert created is not None
    outsider = identity_factory(role_code="owner")
    client = authenticate(outsider)

    for method, url, payload in (
        ("get", agents_path(created.organization_id), None),
        (
            "post",
            agents_path(created.organization_id),
            {"display_name": "x", "category": "other", "version": "1.0"},
        ),
        ("patch", _agent_url(created.organization_id, created.id), {"version": "2.0"}),
        ("delete", _agent_url(created.organization_id, created.id), None),
    ):
        response = client.request(method.upper(), url, json=payload)
        assert response.status_code == 404, f"{method} {url} -> {response.status_code}"

    authenticate(owner_identity)  # back to the tenant that owns the agent
    listing = agents.client.get(agents_path(created.organization_id)).json()
    assert len(listing["items"]) == 1
    assert listing["items"][0]["version"] == created.version


def test_a_caller_whose_membership_is_suspended_loses_access(
    agents: AgentFactory,
    owner_identity: Identity,
    identity_factory: IdentityFactory,
    integration_engine: Engine,
    authenticate,
) -> None:
    """Suspension is enforced on every request, not only at provisioning time."""
    created = agents.register()
    assert created is not None
    actor = identity_factory(role_code="admin", organization_id=owner_identity.organization_id)
    client = authenticate(actor)
    assert client.get(agents_path(actor.organization_id)).status_code == 200

    suspend_membership(integration_engine, actor)
    # 403, not 404: the caller *is* a member of this organization — the membership
    # is just not active — which is the same answer every other route gives.
    for response in (
        client.get(agents_path(actor.organization_id)),
        client.get(_agent_url(actor.organization_id, created.id)),
        client.post(
            agents_path(actor.organization_id),
            json={"display_name": "After Suspension", "category": "other", "version": "1.0"},
        ),
    ):
        assert response.status_code == 403
        assert response.json()["error"]["code"] == "forbidden"
    assert client.get(identity_path(actor.organization_id, created.identity_id)).status_code == 403


def test_an_identifier_from_another_tenant_is_not_a_cross_tenant_key(
    agents: AgentFactory, identity_factory: IdentityFactory, integration_engine: Engine
) -> None:
    """An external identifier is resolved inside the caller's own organization.

    Two tenants may legitimately use the same identifier for their own agents: the
    registry reads it as "the agent this organization knows by that name", so the
    second registration creates its own agent rather than reaching the first one's
    record.
    """
    foreign = identity_factory(role_code="owner")
    foreign_asset_id = insert_asset_row(
        integration_engine,
        organization_id=foreign.organization_id,
        name="Foreign Asset",
        asset_type="agent",
        external_identifier="shared-identifier",
    )
    created = agents.register(
        display_name="Foreign Asset", external_identifier="shared-identifier", version="1.0"
    )
    assert created is not None
    assert created.asset_id != foreign_asset_id
    assert created.organization_id == agents.organization_id


# ── Security ─────────────────────────────────────────────────────────────────


def test_an_agent_response_never_carries_a_credential(
    agents: AgentFactory, owner_identity: Identity
) -> None:
    """An owner is named, never keyed: no token, hash or secret appears anywhere."""
    created = agents.register(owner_user_id=str(owner_identity.user_id))
    assert created is not None
    body = agents.client.get(_agent_url(created.organization_id, created.id)).text
    for forbidden in ("token", "secret", "password", "hash", "bearer", "authorization"):
        assert forbidden not in body.lower()
    assert owner_identity.token not in body


def test_identity_is_generated_and_unique_per_tenant(agents: AgentFactory) -> None:
    """Two registrations never share an identity, and no client input influences it."""
    identities = set()
    for index in range(5):
        record = agents.register(display_name="Same Name", version=f"1.{index}")
        assert record is not None
        identities.add(record.identity_id)
    assert len(identities) == 5

    # The identity survives an update of everything else about the agent.
    record = agents.register(display_name="Renamed Later")
    assert record is not None
    response = agents.client.patch(
        _agent_url(record.organization_id, record.id),
        json={
            "display_name": "Renamed Later v2",
            "category": "security",
            "version": "9.9",
            "framework": "something-else",
            "identity_metadata": {"region": "eu-west-1"},
        },
    )
    assert response.json()["identity_id"] == str(record.identity_id)


def test_the_registry_exposes_no_runtime_control() -> None:
    """Registry state, not control: nothing here starts, stops, blocks or contains.

    The OpenAPI document is the API's own statement of what it offers, so this is
    asserted against it — a route that controlled or contained an agent would have to
    add itself there and fail this test.

    Phase 7 made one word in that list real, and the distinction it draws is the whole
    point: ``/actions/execute`` executes an *action* from a closed catalogue (one
    read-only assessment today), and nothing in the application executes, starts,
    stops, suspends or quarantines an *agent*. The agent registry is still exactly
    three routes, and the assertion below is what keeps "the registry cannot control
    an agent" from quietly becoming false.
    """
    paths = create_app().openapi()["paths"]
    registry_paths = {
        path for path in paths if path == _AGENT_PARENT or path.startswith(f"{_AGENT_PARENT}/")
    }
    assert registry_paths == {
        _AGENT_PARENT,
        f"{_AGENT_PARENT}/identity/{{identity_id}}",
        f"{_AGENT_PARENT}/{{agent_id}}",
    }
    forbidden = ("run", "start", "stop", "kill", "quarantine", "control", "suspend")
    for path in paths:
        assert not any(word in path.lower() for word in forbidden), path

    # ``execute`` appears exactly once in the whole surface, and it is the action
    # firewall — not a route about agents. A client reading the document cannot
    # conclude that an agent may be executed, and cannot reach one by guessing a path.
    executing = sorted(path for path in paths if "execute" in path)
    assert executing == ["/organizations/{organization_id}/actions/execute"]
    assert not any("agent" in path for path in executing)
