"""Phase 4 at the database layer: identity, relationships, constraints, lifecycle.

These tests ask what the *schema* guarantees, not what a handler happens to do:

- an agent's identity is generated by the database, is unique per tenant, and does
  not change when the agent is renamed or its version changes;
- the registry and the inventory are linked one-to-one, and the link is enforced by
  PostgreSQL rather than by remembering to check it in Python;
- an identity cannot be attached to another tenant's asset, to a nonexistent asset,
  or to an asset twice — including when the attempt is raw SQL;
- a lifecycle move the transition table forbids is refused, and ``retired`` is
  terminal;
- the vocabularies (category, version, lifecycle) are closed in the database too;
- deleting the inventory record removes the identity with it, so an orphaned
  identity is not a state the database can reach.

The database-level assertions deliberately use a raw connection for setup: a case
the API is designed to refuse cannot be set up through the API.
"""

from __future__ import annotations

import uuid
from typing import Any

import pytest
from sqlalchemy import Engine, text
from sqlalchemy.exc import DataError, IntegrityError
from sqlalchemy.orm import Session

from agents_fixture import AgentFactory, count_agent_rows, insert_agent_asset
from aicore_api.core.agents import (
    AGENT_INITIAL_STATES,
    AGENT_TRANSITIONS,
    BUILD_REVISION_MAX_LENGTH,
    FRAMEWORK_MAX_LENGTH,
    IDENTITY_METADATA_MAX_BYTES,
    VERSION_MAX_LENGTH,
    AgentCategory,
    normalize_optional_text,
    normalize_version,
    validate_identity_metadata,
    validate_initial_status,
    validate_transition,
)
from aicore_api.core.assets import AssetStatus, AssetType
from aicore_api.core.domain_errors import ConflictError
from aicore_api.db.models.agent import Agent
from aicore_api.db.repositories.agents import AgentRepository, AgentUpdate
from aicore_api.db.repositories.assets import AssetUpdate
from aicore_api.db.tenancy import bind_tenant
from assets_fixture import count_assets
from identity_fixture import Identity, IdentityFactory

# ── The vocabulary itself ────────────────────────────────────────────────────


def test_the_category_vocabulary_is_closed_and_labelled() -> None:
    """Eight categories, each with a human label, and nothing outside them."""
    assert [category.value for category in AgentCategory] == [
        "assistant",
        "workflow",
        "autonomous",
        "coding",
        "customer_support",
        "data",
        "security",
        "other",
    ]
    from aicore_api.core.agents import AGENT_CATEGORY_LABELS

    assert set(AGENT_CATEGORY_LABELS) == {category.value for category in AgentCategory}
    assert all(label.strip() for label in AGENT_CATEGORY_LABELS.values())


def test_only_draft_and_active_can_start_a_record() -> None:
    """Suspended and retired are states an agent moves *to*, not states it starts in."""
    assert {AssetStatus.DRAFT, AssetStatus.ACTIVE} == AGENT_INITIAL_STATES
    for allowed in AGENT_INITIAL_STATES:
        assert validate_initial_status(allowed.value) is allowed
    for refused in (AssetStatus.SUSPENDED, AssetStatus.RETIRED):
        with pytest.raises(ValueError, match=f"cannot start {refused.value}"):
            validate_initial_status(refused.value)


@pytest.mark.parametrize(
    ("current", "requested"),
    [
        ("active", "draft"),
        ("suspended", "draft"),
        ("retired", "active"),
        ("retired", "suspended"),
        ("retired", "draft"),
    ],
)
def test_the_transition_table_is_closed(current: str, requested: str) -> None:
    """Every move outside the table is refused, and the refusal names the reason."""
    with pytest.raises(ValueError):
        validate_transition(current, requested)


@pytest.mark.parametrize(
    ("current", "requested"),
    [
        ("draft", "active"),
        ("draft", "retired"),
        ("active", "suspended"),
        ("suspended", "active"),
        ("active", "retired"),
        ("draft", "draft"),
        ("retired", "retired"),
    ],
)
def test_the_transition_table_allows_what_it_documents(current: str, requested: str) -> None:
    """The documented transitions work, including a no-op on the same state."""
    validate_transition(current, requested)


def test_retired_is_terminal() -> None:
    """Retirement is the one move there is no coming back from."""
    assert AGENT_TRANSITIONS[AssetStatus.RETIRED] == frozenset()
    with pytest.raises(ValueError, match="terminal"):
        validate_transition(AssetStatus.RETIRED, AssetStatus.ACTIVE)


def test_version_labels_are_normalised_not_rejected() -> None:
    """A version is a label: real-world versions must survive, whitespace must not."""
    assert normalize_version("  1.2.0  ") == "1.2.0"
    assert normalize_version("2026-05-18") == "2026-05-18"
    assert normalize_version("0.1.0-rc1") == "0.1.0-rc1"
    assert normalize_version("release train B") == "release train B"
    for unusable in ("", "   ", "\t"):
        with pytest.raises(ValueError, match="version"):
            normalize_version(unusable)
    with pytest.raises(ValueError, match="version"):
        normalize_version("v" * (VERSION_MAX_LENGTH + 1))


def test_optional_registry_text_is_trimmed_and_bounded() -> None:
    """``build_revision`` and ``framework`` behave like the rest of the schema's text."""
    assert normalize_optional_text(None, field_name="framework", max_length=10) is None
    assert normalize_optional_text("  langgraph ", field_name="framework", max_length=10) == (
        "langgraph"
    )
    with pytest.raises(ValueError):
        normalize_optional_text("   ", field_name="framework", max_length=10)
    with pytest.raises(ValueError):
        normalize_optional_text(
            "x" * (FRAMEWORK_MAX_LENGTH + 1),
            field_name="framework",
            max_length=FRAMEWORK_MAX_LENGTH,
        )
    with pytest.raises(ValueError):
        normalize_optional_text(
            "x" * (BUILD_REVISION_MAX_LENGTH + 1),
            field_name="build_revision",
            max_length=BUILD_REVISION_MAX_LENGTH,
        )


def test_identity_metadata_refuses_credentials_outright() -> None:
    """Runtime identity facts are allowed; anything shaped like a secret is not.

    The check runs over the raw keys *and* over the declared fields, so a key that
    merely looks like a credential never reaches the database — and the model's own
    ``extra="forbid"`` means an undeclared key is refused as well.
    """
    accepted = validate_identity_metadata(
        {"runtime": "python3.11", "region": "ap-south-1", "instance": "pod-7"}
    )
    assert accepted == {"runtime": "python3.11", "region": "ap-south-1", "instance": "pod-7"}
    assert validate_identity_metadata(None) is None
    assert validate_identity_metadata({}) is None

    for key in ("api_key", "API_KEY", "token", "secret", "password", "private_key", "credential"):
        with pytest.raises(ValueError, match="credentials"):
            validate_identity_metadata({key: "whatever"})
    with pytest.raises(ValueError):
        validate_identity_metadata({"runtime": "python3.11", "notes": "not a declared field"})
    with pytest.raises(ValueError):
        validate_identity_metadata({"runtime": "  "})
    # The declared fields are what bound a payload, and the model is the reason a
    # credential-shaped key cannot be smuggled in as "extra data": unknown keys are
    # refused before the serialized size is even considered. The byte budget in
    # ``validate_identity_metadata`` is a backstop for whatever a later phase adds
    # to this model — three 64-character labels cannot approach it today.
    assert max(len(name) for name in ("runtime", "region", "instance")) < 32
    assert IDENTITY_METADATA_MAX_BYTES >= 1024
    with pytest.raises(ValueError):
        validate_identity_metadata({"runtime": "x" * 65})


# ── Registration ─────────────────────────────────────────────────────────────


def test_registration_creates_a_record_and_an_identity(
    agents: AgentFactory, owner_identity: Identity, integration_engine: Engine
) -> None:
    """One registration: an ``agent`` asset, plus a registry row pointing at it."""
    record = agents.register(
        display_name="Support Triage",
        category=AgentCategory.ASSISTANT.value,
        version=" 1.0.0 ",
        environment="production",
        owner_user_id=str(owner_identity.user_id),
        framework="langgraph",
        build_revision="abc123",
        identity_metadata={"runtime": "python3.11", "instance": "pod-7"},
    )
    assert record is not None
    body = record.body
    assert body["display_name"] == "Support Triage"
    assert body["category"] == "assistant"
    assert body["version"] == "1.0.0"
    assert body["framework"] == "langgraph"
    assert body["build_revision"] == "abc123"
    assert body["status"] == "draft"
    assert body["environment"] == "production"
    assert body["identity_metadata"] == {"runtime": "python3.11", "instance": "pod-7"}
    assert body["owner"]["user_id"] == str(owner_identity.user_id)

    with bind_tenant(record.organization_id), integration_engine.connect() as connection:
        row = connection.execute(
            text(
                "SELECT a.asset_type, a.discovery_source, a.last_seen_at, g.identity_id, "
                "g.asset_id, g.organization_id "
                "FROM aicore.agents AS g JOIN aicore.assets AS a ON a.id = g.asset_id "
                "WHERE g.organization_id = :organization_id"
            ),
            {"organization_id": str(record.organization_id)},
        ).one()
    assert row.asset_type == AssetType.AGENT.value
    # Registered, not discovered: the provenance says so.
    assert row.discovery_source == "manual"
    assert row.last_seen_at is None
    assert row.identity_id == record.identity_id
    assert row.asset_id == record.asset_id
    assert row.organization_id == record.organization_id


def test_identity_is_generated_by_the_database_and_is_not_the_name(
    agents: AgentFactory, integration_engine: Engine
) -> None:
    """Two agents with the same display name get different identities.

    A name is a label; if identity came from one, two teams with a "Support Triage"
    would be one agent, and renaming either would rewrite history.
    """
    first = agents.register(display_name="Support Triage")
    second = agents.register(display_name="Support Triage")
    assert first is not None and second is not None
    assert first.identity_id != second.identity_id
    assert first.identity_id != first.id

    with integration_engine.connect() as connection:
        # The table name is a bind parameter on purpose: the tenancy guard matches
        # raw SQL textually, and a catalog query that spells out a tenant-owned
        # table's name is (correctly) treated as data access, not reflection.
        stored_default = connection.execute(
            text(
                "SELECT column_default FROM information_schema.columns "
                "WHERE table_schema = 'aicore' AND table_name = :table_name "
                "AND column_name = :column_name"
            ),
            {"table_name": "agents", "column_name": "identity_id"},
        ).scalar_one()
    assert "gen_random_uuid" in stored_default


def test_identity_survives_a_rename_and_a_version_change(agents: AgentFactory) -> None:
    """The whole point of a stable identity: the record changes, the identity does not."""
    created = agents.register(display_name="Support Triage", version="1.0.0")
    assert created is not None
    identity_before = created.identity_id

    for version in ("1.1.0", "2.0.0"):
        response = agents.client.patch(
            f"/organizations/{created.organization_id}/agents/{created.id}",
            json={"display_name": f"Support Triage ({version})", "version": version},
        )
        assert response.status_code == 200, response.text
        assert response.json()["identity_id"] == str(identity_before)
        assert response.json()["version"] == version

    assert created.identity_id == identity_before


def test_a_registration_is_atomic(agents: AgentFactory, integration_engine: Engine) -> None:
    """A refused registration leaves neither a record nor an identity behind."""
    before_assets = count_assets(integration_engine, agents.organization_id)
    before_agents = count_agent_rows(integration_engine, agents.organization_id)

    agents.register(category="not-a-category", expected_status=422)
    agents.register(version="1.0", status="suspended", expected_status=422)

    assert count_assets(integration_engine, agents.organization_id) == before_assets
    assert count_agent_rows(integration_engine, agents.organization_id) == before_agents


def test_registering_the_same_agent_twice_is_refused(agents: AgentFactory) -> None:
    """One agent, one identity: a second registration of the same identifier is a 409."""
    first = agents.register(display_name="Support Triage", external_identifier="triage-1")
    assert first is not None
    refused = agents.register(
        display_name="Support Triage", external_identifier="triage-1", expected_status=409
    )
    assert refused is None

    listed = agents.client.get(f"/organizations/{first.organization_id}/agents").json()
    assert [item["identity_id"] for item in listed["items"]] == [str(first.identity_id)]


def test_an_existing_agent_asset_is_adopted_not_duplicated(
    agents: AgentFactory, owner_identity: Identity, integration_engine: Engine
) -> None:
    """An inventory that already knows the agent gains an identity; it is not copied.

    This is the situation an organization is in when its inventory predates the
    registry: the asset exists. Registering it attaches the identity to that record,
    fills an owner slot that was empty, and changes nothing that was already decided.
    """
    asset_id = insert_agent_asset(
        integration_engine,
        organization_id=agents.organization_id,
        name="Legacy Agent",
        external_identifier="legacy-1",
        environment="staging",
    )
    adopted = agents.register(
        display_name="Legacy Agent",
        category=AgentCategory.DATA.value,
        version="0.9",
        environment="staging",
        owner_user_id=str(owner_identity.user_id),
        external_identifier="legacy-1",
    )
    assert adopted is not None
    assert adopted.asset_id == asset_id

    with bind_tenant(agents.organization_id), integration_engine.connect() as connection:
        asset_count = connection.execute(
            text(
                "SELECT count(*) FROM aicore.assets WHERE organization_id = :organization_id "
                "AND asset_type = 'agent' AND external_identifier = 'legacy-1'"
            ),
            {"organization_id": str(agents.organization_id)},
        ).scalar_one()
        owner = connection.execute(
            text(
                "SELECT owner_membership_id FROM aicore.assets WHERE id = :asset_id "
                "AND organization_id = :organization_id"
            ),
            {"asset_id": str(asset_id), "organization_id": str(agents.organization_id)},
        ).scalar_one()
    assert asset_count == 1
    assert owner == owner_identity.membership_id


def test_adoption_refuses_to_overwrite_what_is_recorded(
    agents: AgentFactory, identity_factory: IdentityFactory, integration_engine: Engine
) -> None:
    """A registration that contradicts the existing record is refused, not applied.

    Every claim a registration is *allowed* to make is tried against a record that
    says something else: the name, the environment, the lifecycle state and the
    owner. Each is a 409, and afterwards the record is byte-for-byte what it was —
    which is the property that makes adopting an existing asset safe.
    """
    insert_agent_asset(
        integration_engine,
        organization_id=agents.organization_id,
        name="Legacy Agent",
        external_identifier="legacy-2",
        environment="staging",
        status="active",
    )
    for contradiction in (
        {"display_name": "A Different Name"},
        {"environment": "production"},
        {"status": "draft"},
    ):
        refused = agents.register(
            category=AgentCategory.DATA.value,
            version="0.9",
            external_identifier="legacy-2",
            **contradiction,
            expected_status=409,
        )
        assert refused is None

    with bind_tenant(agents.organization_id), integration_engine.connect() as connection:
        row = connection.execute(
            text(
                "SELECT name, environment, status, owner_membership_id FROM aicore.assets "
                "WHERE organization_id = :organization_id AND external_identifier = 'legacy-2'"
            ),
            {"organization_id": str(agents.organization_id)},
        ).one()
    assert row.name == "Legacy Agent"
    assert row.environment == "staging"
    assert row.status == "active"
    assert row.owner_membership_id is None
    assert count_agent_rows(integration_engine, agents.organization_id) == 0


def test_adoption_fills_an_empty_owner_slot_without_choosing_an_owner_itself(
    agents: AgentFactory,
    owner_identity: Identity,
    identity_factory: IdentityFactory,
    integration_engine: Engine,
) -> None:
    """Filling a gap is allowed; replacing a decision is not.

    Two records, two answers. An unowned asset gains the owner the registration
    names, because nothing is being overwritten. An asset that already has an owner
    refuses a registration that names somebody else — a 409, not a reassignment —
    because ownership is a decision an operator made, and re-registering an agent is
    not a way to undo it.
    """
    other_member = identity_factory.join(
        identity_factory(role_code="viewer"),
        organization_id=agents.organization_id,
        role_code="viewer",
    )
    other_membership_id = next(
        membership_id
        for organization_id, membership_id in other_member.memberships()
        if organization_id == agents.organization_id
    )

    unowned_asset_id = insert_agent_asset(
        integration_engine,
        organization_id=agents.organization_id,
        name="Unowned Agent",
        external_identifier="legacy-3",
    )
    filled = agents.register(
        display_name="Unowned Agent",
        category=AgentCategory.DATA.value,
        version="0.9",
        external_identifier="legacy-3",
        owner_user_id=str(other_member.user_id),
    )
    assert filled is not None
    assert filled.asset_id == unowned_asset_id
    assert filled.body["owner"]["membership_id"] == str(other_membership_id)

    owned_asset_id = insert_agent_asset(
        integration_engine,
        organization_id=agents.organization_id,
        name="Owned Agent",
        external_identifier="legacy-4",
        owner_membership_id=other_membership_id,
    )
    refused = agents.register(
        display_name="Owned Agent",
        category=AgentCategory.DATA.value,
        version="0.9",
        external_identifier="legacy-4",
        # A different, entirely valid, active member of this organization: the
        # refusal is about what is already recorded, not about who is asking.
        owner_user_id=str(owner_identity.user_id),
        expected_status=409,
    )
    assert refused is None
    with bind_tenant(agents.organization_id), integration_engine.connect() as connection:
        owner = connection.execute(
            text(
                "SELECT owner_membership_id FROM aicore.assets WHERE id = :asset_id "
                "AND organization_id = :organization_id"
            ),
            {"asset_id": str(owned_asset_id), "organization_id": str(agents.organization_id)},
        ).scalar_one()
    assert owner == other_membership_id
    assert count_agent_rows(integration_engine, agents.organization_id) == 1


# ── Reads and filters ────────────────────────────────────────────────────────


def test_lookup_by_identity_and_by_registry_id_agree(agents: AgentFactory) -> None:
    """Both lookups return the same agent; neither is a second source of truth."""
    created = agents.register()
    assert created is not None
    by_id = agents.client.get(
        f"/organizations/{created.organization_id}/agents/{created.id}"
    ).json()
    by_identity = agents.client.get(
        f"/organizations/{created.organization_id}/agents/identity/{created.identity_id}"
    ).json()
    assert by_id == by_identity


def test_filters_narrow_the_page(agents: AgentFactory, owner_identity: Identity) -> None:
    """Category filters the registry; status, environment and owner filter the record."""
    agents.register(display_name="Assistant One", category="assistant", environment="production")
    agents.register(display_name="Coding One", category="coding", environment="staging")
    coding = agents.register(display_name="Coding Two", category="coding", environment="staging")
    assert coding is not None
    agents.client.patch(
        f"/organizations/{coding.organization_id}/agents/{coding.id}", json={"status": "active"}
    )
    agents.client.patch(
        f"/organizations/{coding.organization_id}/agents/{coding.id}",
        json={"owner_user_id": str(owner_identity.user_id)},
    )

    def names(**params: Any) -> list[str]:
        response = agents.client.get(
            f"/organizations/{coding.organization_id}/agents", params=params
        )
        assert response.status_code == 200, response.text
        return sorted(item["display_name"] for item in response.json()["items"])

    assert names(category="coding") == ["Coding One", "Coding Two"]
    assert names(category=["coding", "assistant"]) == [
        "Assistant One",
        "Coding One",
        "Coding Two",
    ]
    assert names(status="active") == ["Coding Two"]
    assert names(environment="staging") == ["Coding One", "Coding Two"]
    assert names(owner_membership_id=str(owner_identity.membership_id)) == ["Coding Two"]
    assert names(category="coding", environment="production") == []


def test_the_page_is_bounded_ordered_and_pageable(agents: AgentFactory) -> None:
    """Newest first, with a total only when it is asked for."""
    created = agents.register(display_name="First Agent")
    assert created is not None
    for index in range(3):
        agents.register(display_name=f"Agent {index}")

    first_page = agents.client.get(
        f"/organizations/{created.organization_id}/agents", params={"limit": 2}
    ).json()
    assert first_page["count"] == 2
    assert first_page["total"] is None
    assert first_page["limit"] == 2
    assert len(first_page["items"]) == 2

    with_total = agents.client.get(
        f"/organizations/{created.organization_id}/agents", params={"total": "true"}
    ).json()
    assert with_total["total"] == 4

    second_page = agents.client.get(
        f"/organizations/{created.organization_id}/agents",
        params={"limit": 2, "offset": 2},
    ).json()
    assert {item["id"] for item in first_page["items"]}.isdisjoint(
        {item["id"] for item in second_page["items"]}
    )

    for bad in ({"limit": 0}, {"limit": 201}, {"offset": -1}, {"offset": 100_001}):
        assert (
            agents.client.get(
                f"/organizations/{created.organization_id}/agents", params=bad
            ).status_code
            == 422
        )


# ── Lifecycle, through the API ───────────────────────────────────────────────


def test_lifecycle_moves_are_recorded_and_impossible_ones_refused(
    agents: AgentFactory,
) -> None:
    """``active → suspended → active → retired`` works; ``retired → active`` does not.

    Suspension is a record. Nothing is stopped, blocked or revoked by moving an agent
    to ``suspended`` — this build has no runtime to control, and the test asserts the
    move (a stored state) rather than an effect it cannot have.
    """
    created = agents.register(status="active")
    assert created is not None
    path = f"/organizations/{created.organization_id}/agents/{created.id}"

    def move(target: str) -> Any:
        return agents.client.patch(path, json={"status": target})

    assert move("suspended").json()["status"] == "suspended"
    assert move("active").json()["status"] == "active"
    assert move("retired").json()["status"] == "retired"

    refused = move("active")
    assert refused.status_code == 409
    assert "terminal" in refused.json()["error"]["message"]
    assert agents.client.get(path).json()["status"] == "retired"


def test_errors_use_the_application_envelope(agents: AgentFactory) -> None:
    """A refusal is a structured error, not a driver message."""
    created = agents.register()
    assert created is not None
    response = agents.client.patch(
        f"/organizations/{created.organization_id}/agents/{created.id}",
        json={"status": "suspended"},
    )
    assert response.status_code == 409
    body = response.json()
    assert set(body) == {"error"}
    assert body["error"]["code"]
    assert "request_id" in body["error"]


# ── Cross-tenant behaviour, at the database ─────────────────────────────────


def test_a_tenant_cannot_reach_another_tenants_agent(
    agents: AgentFactory, identity_factory: IdentityFactory, integration_session: Session
) -> None:
    """Repository lookups are tenant-scoped: a foreign row reads as no row.

    The other tenant is real — it has its own organization and its own owner — and
    the agent it cannot see is real too. Nothing about the answer distinguishes
    "belongs to somebody else" from "does not exist".
    """
    created = agents.register()
    assert created is not None
    other = identity_factory(role_code="owner")
    repository = AgentRepository(integration_session, other.organization_id)
    assert repository.find(created.id) is None
    assert repository.find_by_identity(created.identity_id) is None
    assert repository.find_by_asset(created.asset_id) is None
    assert repository.page(limit=10, offset=0) == []
    assert repository.count() == 0


def test_the_database_refuses_an_identity_for_another_tenants_asset(
    agents: AgentFactory, identity_factory: IdentityFactory, integration_engine: Engine
) -> None:
    """The composite foreign key, not application code, is what prevents this.

    Two tenants, one asset belonging to the second. A registry row claiming the first
    tenant while pointing at it is refused by PostgreSQL — the constraint is on
    ``(organization_id, asset_id)``, so "the agent's asset belongs to the agent's
    organization" is a property of the schema.
    """
    other = identity_factory(role_code="owner")
    foreign_asset_id = insert_agent_asset(
        integration_engine, organization_id=other.organization_id, name="Foreign Agent"
    )
    with pytest.raises(IntegrityError) as captured:
        agents.register_row(asset_id=foreign_asset_id)
    assert "fk_agents_organization_id_assets" in str(captured.value.orig)


def test_the_database_refuses_an_identity_without_an_asset(
    agents: AgentFactory, integration_engine: Engine
) -> None:
    """A registry row for an asset that does not exist cannot be inserted."""
    with pytest.raises(IntegrityError) as captured:
        agents.register_row(asset_id=uuid.uuid4())
    assert "fk_agents_organization_id_assets" in str(captured.value.orig)


def test_the_database_refuses_two_identities_for_one_asset(
    agents: AgentFactory,
) -> None:
    """``asset_id`` is unique: one agent cannot hold two identities."""
    created = agents.register()
    assert created is not None
    with pytest.raises(IntegrityError) as captured:
        agents.register_row(asset_id=created.asset_id)
    assert "uq_agents_asset_id" in str(captured.value.orig)


def test_the_database_refuses_a_duplicate_identity_in_one_tenant(
    agents: AgentFactory, integration_engine: Engine
) -> None:
    """Identity is unique per organization, so a lookup cannot be ambiguous."""
    created = agents.register()
    assert created is not None
    second_asset_id = insert_agent_asset(
        integration_engine, organization_id=agents.organization_id, name="Second Agent"
    )
    with pytest.raises(IntegrityError) as captured:
        agents.register_row(asset_id=second_asset_id, identity_id=created.identity_id)
    assert "uq_agents_organization_id_identity_id" in str(captured.value.orig)


@pytest.mark.parametrize(
    ("field", "value", "constraint"),
    [
        ("category", "sentient", "ck_agents_category_valid"),
        ("category", "", "ck_agents_category_valid"),
        ("version", "   ", "ck_agents_version_length"),
    ],
)
def test_the_database_refuses_a_value_outside_a_documented_vocabulary(
    agents: AgentFactory, integration_engine: Engine, field: str, value: str, constraint: str
) -> None:
    """Every closed vocabulary is enforced in the schema, not only in Pydantic."""
    asset_id = insert_agent_asset(
        integration_engine, organization_id=agents.organization_id, name="Vocabulary Agent"
    )
    with pytest.raises(IntegrityError) as captured:
        agents.register_row(asset_id=asset_id, **{field: value})
    assert constraint in str(captured.value.orig)


def test_the_column_itself_bounds_the_version_label(
    agents: AgentFactory, integration_engine: Engine
) -> None:
    """A version longer than the column is refused by the type, before any check runs.

    Two layers, two answers: a blank label violates the check constraint, an
    over-long one is oversized for ``varchar(64)``. Both are refusals, and the test
    keeps them distinct so neither layer can quietly stop working.
    """
    asset_id = insert_agent_asset(
        integration_engine, organization_id=agents.organization_id, name="Long Version Agent"
    )
    with pytest.raises(DataError, match="too long"):
        agents.register_row(asset_id=asset_id, version="v" * (VERSION_MAX_LENGTH + 1))


def test_the_database_refuses_identity_metadata_that_is_not_an_object(
    agents: AgentFactory, integration_engine: Engine
) -> None:
    """A JSON scalar in the metadata column is a shape no reader can rely on."""
    asset_id = insert_agent_asset(
        integration_engine, organization_id=agents.organization_id, name="Metadata Agent"
    )
    for value in ('"just-a-string"', "7", '["runtime"]'):
        # A distinct asset per attempt: the unique constraint on asset_id would
        # otherwise decide the outcome before the metadata check is reached.
        attempt_asset_id = (
            asset_id
            if value == '"just-a-string"'
            else insert_agent_asset(
                integration_engine,
                organization_id=agents.organization_id,
                name=f"Metadata Agent {value}",
            )
        )
        with (
            pytest.raises(IntegrityError) as captured,
            bind_tenant(agents.organization_id),
            integration_engine.begin() as connection,
        ):
            connection.execute(
                text(
                    "INSERT INTO aicore.agents "
                    "(organization_id, asset_id, category, version, identity_metadata) "
                    "VALUES (:organization_id, :asset_id, 'assistant', '1.0', "
                    "CAST(:metadata AS jsonb))"
                ),
                {
                    "organization_id": str(agents.organization_id),
                    "asset_id": str(attempt_asset_id),
                    "metadata": value,
                },
            )
        assert "ck_agents_identity_metadata_is_object" in str(captured.value.orig)


# ── Deletion ─────────────────────────────────────────────────────────────────


def test_deleting_an_agent_removes_its_identity_and_its_record(
    agents: AgentFactory, integration_engine: Engine
) -> None:
    """No orphans: the registry's foreign key cascades from the inventory row."""
    created = agents.register()
    assert created is not None
    response = agents.client.delete(f"/organizations/{created.organization_id}/agents/{created.id}")
    assert response.status_code == 204

    with bind_tenant(created.organization_id), integration_engine.connect() as connection:
        agent_rows = connection.execute(
            text(
                "SELECT count(*) FROM aicore.agents WHERE asset_id = :asset_id "
                "AND organization_id = :organization_id"
            ),
            {"asset_id": str(created.asset_id), "organization_id": str(created.organization_id)},
        ).scalar_one()
        asset_rows = connection.execute(
            text(
                "SELECT count(*) FROM aicore.assets WHERE id = :asset_id "
                "AND organization_id = :organization_id"
            ),
            {"asset_id": str(created.asset_id), "organization_id": str(created.organization_id)},
        ).scalar_one()
    assert agent_rows == 0
    assert asset_rows == 0
    assert count_agent_rows(integration_engine, agents.organization_id) == 0


def test_removing_the_inventory_record_removes_the_identity(
    agents: AgentFactory, integration_engine: Engine
) -> None:
    """The cascade is a property of the schema, not of one code path."""
    created = agents.register()
    assert created is not None
    with bind_tenant(agents.organization_id), integration_engine.begin() as connection:
        connection.execute(
            text(
                "DELETE FROM aicore.assets WHERE id = :asset_id "
                "AND organization_id = :organization_id"
            ),
            {"asset_id": str(created.asset_id), "organization_id": str(agents.organization_id)},
        )
    assert count_agent_rows(integration_engine, agents.organization_id) == 0


def test_an_organization_with_agents_cannot_be_deleted_by_accident(
    agents: AgentFactory, integration_engine: Engine
) -> None:
    """The tenant boundary is RESTRICT: removing a tenant is an explicit procedure.

    The memberships are removed first so the refusal can only come from the
    registry: an organization whose agents still exist cannot be deleted, and the
    error names the registry's own foreign key.
    """
    agents.register()
    with (
        bind_tenant(agents.organization_id),
        integration_engine.begin() as connection,
    ):
        connection.execute(
            text("DELETE FROM aicore.memberships WHERE organization_id = :organization_id"),
            {"organization_id": str(agents.organization_id)},
        )
    with (
        pytest.raises(IntegrityError) as captured,
        bind_tenant(agents.organization_id),
        integration_engine.begin() as connection,
    ):
        connection.execute(
            text("DELETE FROM aicore.organizations WHERE id = :organization_id"),
            {"organization_id": str(agents.organization_id)},
        )
    # The asset is what PostgreSQL reports first — the registry row references the
    # asset, and the asset references the tenant. The registry holds its own
    # RESTRICT reference as well, asserted structurally below, so the boundary does
    # not depend on which of the two columns answers first.
    assert "fk_assets_organization_id_organizations" in str(captured.value.orig)
    with bind_tenant(agents.organization_id), integration_engine.connect() as connection:
        remaining = connection.execute(
            text("SELECT count(*) FROM aicore.agents WHERE organization_id = :organization_id"),
            {"organization_id": str(agents.organization_id)},
        ).scalar_one()
    assert remaining == 1


def test_the_registry_references_the_tenant_and_its_record_explicitly(
    integration_engine: Engine,
) -> None:
    """Both references, and what they do on delete, are readable from the catalog.

    ``(organization_id, asset_id) → assets`` cascades, because an identity whose
    agent is gone is an orphan. ``organization_id → organizations`` restricts, so a
    tenant cannot be removed out from under its registry by a cascade. The second is
    redundant while the first exists, and it is there on purpose: the tenant boundary
    of this table should not depend on another table's constraint.
    """
    with integration_engine.connect() as connection:
        constraints = dict(
            connection.execute(
                text(
                    "SELECT conname, pg_get_constraintdef(oid) FROM pg_constraint "
                    "WHERE conrelid = to_regclass(CAST(:qualified AS text))"
                ),
                {"qualified": "aicore.agents"},
            ).all()
        )
    assert constraints["fk_agents_organization_id_assets"] == (
        "FOREIGN KEY (organization_id, asset_id) REFERENCES assets(organization_id, id) "
        "ON DELETE CASCADE"
    )
    assert constraints["fk_agents_organization_id_organizations"] == (
        "FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT"
    )


def test_a_lifecycle_move_that_is_not_allowed_is_a_conflict(
    agents: AgentFactory, integration_session: Session
) -> None:
    """The rule lives in the repository, so every write path obeys it."""
    created = agents.register(status="active")
    assert created is not None
    repository = AgentRepository(integration_session, created.organization_id)
    agent = repository.find(created.id)
    assert agent is not None
    with pytest.raises(ConflictError, match="cannot move"):
        repository.update(agent, AgentUpdate(asset=AssetUpdate(status="draft")))


def test_moving_to_the_same_state_changes_nothing(
    agents: AgentFactory, integration_session: Session
) -> None:
    """A no-op is reported as a no-op, so nothing is emitted for it."""
    created = agents.register(status="active")
    assert created is not None
    repository = AgentRepository(integration_session, created.organization_id)
    agent = repository.find(created.id)
    assert agent is not None
    assert repository.update(agent, AgentUpdate(asset=AssetUpdate(status="active"))) == []


def test_clearing_registry_fields_is_explicit(agents: AgentFactory) -> None:
    """``null`` removes a field; omitting it leaves the field alone."""
    created = agents.register(framework="langgraph", build_revision="abc123")
    assert created is not None
    path = f"/organizations/{created.organization_id}/agents/{created.id}"

    untouched = agents.client.patch(path, json={"version": "1.0.1"}).json()
    assert untouched["framework"] == "langgraph"
    assert untouched["build_revision"] == "abc123"

    cleared = agents.client.patch(path, json={"framework": None, "build_revision": None}).json()
    assert cleared["framework"] is None
    assert cleared["build_revision"] is None
    assert cleared["version"] == "1.0.1"


def test_an_unknown_registry_field_is_refused(agents: AgentFactory) -> None:
    """A client that sends a field this build does not have is told so."""
    created = agents.register()
    assert created is not None
    response = agents.client.patch(
        f"/organizations/{created.organization_id}/agents/{created.id}",
        json={"risk_score": 9},
    )
    assert response.status_code == 422
    refused = agents.register(trust_level="high", expected_status=422)
    assert refused is None


def test_the_registry_does_not_duplicate_inventory_state(
    agents: AgentFactory, integration_engine: Engine
) -> None:
    """Name, status, environment and owner live on the asset — there is no second copy.

    Asserted against the schema, because the design decision this phase makes is that
    the registry holds identity and registry facts only. A column added here to
    "cache" the display name would be a second thing to keep in sync, and this test
    is where that decision is recorded.
    """
    columns = {
        "id",
        "organization_id",
        "identity_id",
        "asset_id",
        "category",
        "version",
        "build_revision",
        "framework",
        "identity_metadata",
        "created_at",
        "updated_at",
    }
    with integration_engine.connect() as connection:
        actual = {
            row[0]
            for row in connection.execute(
                text(
                    "SELECT column_name FROM information_schema.columns "
                    "WHERE table_schema = 'aicore' AND table_name = :table_name"
                ),
                {"table_name": "agents"},
            )
        }
    assert actual == columns
    assert not {"name", "display_name", "status", "environment", "owner_membership_id"} & actual


def test_the_registry_is_reachable_only_through_its_tenant(
    agents: AgentFactory, integration_engine: Engine
) -> None:
    """A raw read without a bound tenant is refused, as for any tenant-owned table."""
    from aicore_api.db.tenancy import TenantScopeError

    with pytest.raises(TenantScopeError), integration_engine.connect() as connection:
        connection.execute(text("SELECT count(*) FROM aicore.agents"))


def test_the_agent_model_matches_the_migrated_schema(integration_engine: Engine) -> None:
    """No drift between ``Agent`` and the table migration 0004 created."""
    from sqlalchemy import inspect

    inspector = inspect(integration_engine)
    assert inspector.has_table("agents", schema="aicore")
    columns = {column["name"] for column in inspector.get_columns("agents", schema="aicore")}
    assert columns == {column.name for column in Agent.__table__.columns}

    unique = {
        tuple(constraint["column_names"])
        for constraint in inspector.get_unique_constraints("agents", schema="aicore")
    }
    assert ("asset_id",) in unique
    assert ("organization_id", "identity_id") in unique
