"""Organization persistence and its database constraints.

The tenant registry is the one table that is intentionally *not* tenant-owned, so
these tests exercise it through :class:`OrganizationRepository` directly.
"""

from __future__ import annotations

import uuid

import pytest
from sqlalchemy import Engine, text
from sqlalchemy.orm import Session

from aicore_api.core.domain_errors import ConflictError, NotFoundError
from aicore_api.db.models.organization import OrganizationStatus
from aicore_api.db.repositories.organizations import OrganizationRepository

pytestmark = pytest.mark.integration


def test_organization_is_persisted_and_readable(
    integration_session: Session,
    integration_engine: Engine,
) -> None:
    """A created tenant is durable — read back through a different connection."""
    repository = OrganizationRepository(integration_session)
    slug = f"acme-{uuid.uuid4().hex[:8]}"

    created = repository.create(name="Acme Corporation", slug=slug)

    assert created.id is not None  # generated by the database, not the client
    assert created.status == OrganizationStatus.ACTIVE
    assert created.created_at is not None
    assert created.updated_at is not None

    with integration_engine.connect() as connection:
        stored = connection.execute(
            text("SELECT name, slug, status FROM aicore.organizations WHERE id = :id"),
            {"id": created.id},
        ).one()

    assert stored == ("Acme Corporation", slug, "active")


def test_slug_is_unique(integration_session: Session) -> None:
    """Two tenants cannot share a slug — the database decides, not a pre-check."""
    repository = OrganizationRepository(integration_session)
    slug = f"duplicate-{uuid.uuid4().hex[:8]}"

    repository.create(name="First", slug=slug)

    with pytest.raises(ConflictError, match="already exists"):
        repository.create(name="Second", slug=slug)


def test_get_returns_the_organization(integration_session: Session) -> None:
    repository = OrganizationRepository(integration_session)
    created = repository.create(name="Globex", slug=f"globex-{uuid.uuid4().hex[:8]}")

    found = repository.get(created.id)

    assert found.id == created.id
    assert found.name == "Globex"


def test_unknown_organization_raises_not_found(integration_session: Session) -> None:
    """An unknown tenant id is rejected, not silently returned as nothing."""
    repository = OrganizationRepository(integration_session)

    with pytest.raises(NotFoundError):
        repository.get(uuid.uuid4())


def test_find_by_slug_returns_none_for_an_unknown_slug(integration_session: Session) -> None:
    repository = OrganizationRepository(integration_session)

    assert repository.find_by_slug(f"missing-{uuid.uuid4().hex[:8]}") is None


def test_status_defaults_to_active_in_the_database(
    integration_engine: Engine,
    integration_session: Session,
) -> None:
    """The default lives in the schema, so a row inserted without it is still valid."""
    slug = f"default-{uuid.uuid4().hex[:8]}"
    organization_id = uuid.uuid4()

    with integration_engine.connect() as connection:
        connection.execute(
            text("INSERT INTO aicore.organizations (id, name, slug) VALUES (:id, :name, :slug)"),
            {"id": organization_id, "name": "Defaulted", "slug": slug},
        )
        status = connection.execute(
            text("SELECT status FROM aicore.organizations WHERE id = :id"),
            {"id": organization_id},
        ).scalar_one()

    assert status == "active"


def test_slug_format_is_enforced_by_the_database(
    integration_engine: Engine,
) -> None:
    """A CHECK constraint rejects a malformed slug even for a direct write."""
    from sqlalchemy.exc import IntegrityError

    with integration_engine.connect() as connection, pytest.raises(IntegrityError):
        connection.execute(
            text("INSERT INTO aicore.organizations (id, name, slug) VALUES (:id, :name, :slug)"),
            {"id": uuid.uuid4(), "name": "Bad Slug", "slug": "Not A Slug!"},
        )


def test_status_values_are_constrained(integration_engine: Engine) -> None:
    """An unknown status is a database error, not a value that quietly persists."""
    from sqlalchemy.exc import IntegrityError

    with integration_engine.connect() as connection, pytest.raises(IntegrityError):
        connection.execute(
            text(
                "INSERT INTO aicore.organizations (id, name, slug, status) "
                "VALUES (:id, :name, :slug, :status)"
            ),
            {
                "id": uuid.uuid4(),
                "name": "Bad Status",
                "slug": f"bad-status-{uuid.uuid4().hex[:8]}",
                "status": "deleted-by-hand",
            },
        )


def test_empty_name_is_rejected(integration_engine: Engine) -> None:
    """Names are trimmed and length-checked in the schema."""
    from sqlalchemy.exc import IntegrityError

    with integration_engine.connect() as connection, pytest.raises(IntegrityError):
        connection.execute(
            text("INSERT INTO aicore.organizations (id, name, slug) VALUES (:id, :name, :slug)"),
            {"id": uuid.uuid4(), "name": "   ", "slug": f"blank-{uuid.uuid4().hex[:8]}"},
        )


def test_organizations_cannot_be_deleted_while_tenant_data_exists(
    integration_session: Session,
    tenant_sample_table: str,
    two_organizations: tuple[uuid.UUID, uuid.UUID],
) -> None:
    """``ON DELETE RESTRICT``: removing a tenant is never a cascade side effect."""
    from sqlalchemy.exc import IntegrityError

    from tenant_fixture import insert_sample

    tenant_a, _ = two_organizations
    insert_sample(integration_session, tenant_a, "acme-agent")
    integration_session.commit()

    with pytest.raises(IntegrityError):
        integration_session.execute(
            text("DELETE FROM aicore.organizations WHERE id = :id"), {"id": tenant_a}
        )


def test_organizations_table_has_a_primary_key_and_timestamps(
    integration_engine: Engine,
) -> None:
    """The schema itself: the columns Phase 1 promised are the columns that exist."""
    with integration_engine.connect() as connection:
        columns = dict(
            connection.execute(
                text(
                    "SELECT column_name, is_nullable FROM information_schema.columns "
                    "WHERE table_schema = 'aicore' AND table_name = 'organizations'"
                )
            ).all()
        )
        constraints = {
            row[0]
            for row in connection.execute(
                text(
                    "SELECT constraint_name FROM information_schema.table_constraints "
                    "WHERE table_schema = 'aicore' AND table_name = 'organizations'"
                )
            ).all()
        }

    assert set(columns) == {"id", "name", "slug", "status", "created_at", "updated_at"}
    assert all(nullable == "NO" for nullable in columns.values())
    assert "pk_organizations" in constraints
    assert "uq_organizations_slug" in constraints
    assert "ck_organizations_slug_format" in constraints
    assert "ck_organizations_status_valid" in constraints


def test_repr_does_not_expose_tenant_data(integration_session: Session) -> None:
    """Logs are not the place to learn a customer's name."""
    repository = OrganizationRepository(integration_session)
    created = repository.create(name="Confidential Customer", slug=f"conf-{uuid.uuid4().hex[:8]}")

    assert "Confidential Customer" not in repr(created)
    assert created.slug not in repr(created)
