"""Declarative base and the conventions every AICore table follows.

Three rules are encoded here rather than repeated per model:

1. **Deterministic constraint names.** The naming convention below means every
   primary key, foreign key, unique and check constraint has a predictable name.
   Migrations can then be written (and reversed) without guessing, and a schema
   diff is reviewable.
2. **Every table is in the ``aicore`` schema.** The namespace is created by the
   migration environment, so application objects never mix with PostgreSQL's.
3. **Tenant ownership is a base class, not a convention people remember.**
   A table that belongs to an organization inherits :class:`TenantOwnedMixin`,
   which adds a mandatory ``organization_id`` foreign key. Inheritance is what
   makes a table *detectable* as tenant-owned at runtime — the isolation guard in
   :mod:`aicore_api.db.tenancy` uses exactly that to refuse unscoped queries.

Identifiers are UUIDs: they are generated by the database (``gen_random_uuid()``,
built into PostgreSQL 13+), so a client cannot choose or predict one.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, MetaData, func
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

#: The PostgreSQL schema that holds every AICore table. Created by
#: ``database/migrations/env.py`` before the first migration runs, and again
#: (idempotently) by the first revision.
APP_SCHEMA = "aicore"

#: Constraint names are part of the migration surface: keep them deterministic.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base for every AICore model.

    ``schema=APP_SCHEMA`` on the metadata means models declare plain table names
    and cannot accidentally omit the namespace.
    """

    metadata = MetaData(schema=APP_SCHEMA, naming_convention=NAMING_CONVENTION)


class UUIDPrimaryKeyMixin:
    """A database-generated UUID primary key.

    The server default (not a Python-side default) is deliberate: rows created
    by migrations, data fixes or future bulk loads get an identifier too.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
    )


class TimestampMixin:
    """``created_at`` / ``updated_at``, maintained in UTC.

    ``TIMESTAMP WITH TIME ZONE`` (not a naive timestamp) — an audit trail that
    loses its offset is not an audit trail.

    ``updated_at`` is refreshed by the ORM on UPDATE. A database trigger would
    catch writes made outside the ORM; that is deferred until there is a
    non-ORM writer, because a trigger is a schema object that must be migrated,
    versioned and tested like everything else here.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )


class TenantOwnedMixin:
    """Marks a table as belonging to exactly one organization.

    This is the tenant boundary. Two properties matter for security:

    - It is ``NOT NULL``: a row can never be tenant-less.
    - The foreign key uses ``ON DELETE RESTRICT``: deleting an organization
      cannot silently cascade into (or orphan) its data. Removing a tenant is an
      explicit operational procedure, not a side effect of a DELETE.

    ``index=True`` because "everything for this organization" is the primary
    access pattern in a multi-tenant system.
    """

    organization_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey(f"{APP_SCHEMA}.organizations.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
