"""Agent contract: what a client may send when registering an agent, and what it gets back.

Two rules shape these models, and they are the inventory's rules because an agent is
an inventory record with an identity layer on top.

**Identity is not writable.** There is no ``identity_id``, ``organization_id`` or
``asset_id`` in a request model: the client chooses what the agent *is called*,
never *who it is*. The display name is a label that changes; the identity is
generated by the database and cannot be set, spoofed or carried in a body. Anything
that would let a caller name an identity — a made-up identifier, an ``id``
override — is refused by ``extra="forbid"`` rather than ignored.

**Closed where the value is a decision, open only where it is metadata.** ``category``
and ``status`` are typed as their vocabularies, so an invented category or lifecycle
state is a 422 at the boundary and never reaches a check constraint. ``identity_metadata``
is a small closed model too (runtime, region, instance): what belongs in it is a
decision, and free-form runtime metadata would be where credentials eventually got
pasted.

``display_name`` rather than ``name`` because that is the vocabulary of agent
identity: it is what an operator sees, and it is pointedly *not* the identity.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any, Self

from pydantic import BaseModel, ConfigDict, Field, model_validator

from aicore_api.core.agents import (
    BUILD_REVISION_MAX_LENGTH,
    FRAMEWORK_MAX_LENGTH,
    VERSION_MAX_LENGTH,
    AgentCategory,
)
from aicore_api.core.assets import AssetStatus, Environment
from aicore_api.db.models.asset import (
    DESCRIPTION_MAX_LENGTH,
    EXTERNAL_IDENTIFIER_MAX_LENGTH,
    NAME_MAX_LENGTH,
)
from aicore_api.schemas.assets import AssetOwnerRead

__all__ = [
    "AgentCreate",
    "AgentListResponse",
    "AgentOwnerRead",
    "AgentRead",
    "AgentUpdateRequest",
]

#: Fields that must carry a value when they appear in a PATCH at all. Everything
#: else in :class:`AgentUpdateRequest` is clearable: an explicit ``null`` removes
#: the value, and ``clears()`` is how the route reads that intent. "Clear the
#: display name" or "clear the version" are not operations that should silently
#: succeed — an agent without either is one nobody can identify in a list.
_REQUIRED_WHEN_PRESENT = ("display_name", "status", "environment", "category", "version")

#: The owner shape is the inventory's, deliberately: it already names the
#: membership that the asset actually references alongside the user it belongs to,
#: and a second, slightly different owner model would be two answers to one question.
AgentOwnerRead = AssetOwnerRead


class AgentCreate(BaseModel):
    """Request body for ``POST /organizations/{organization_id}/agents``."""

    model_config = ConfigDict(extra="forbid")

    display_name: str = Field(
        min_length=1,
        max_length=NAME_MAX_LENGTH,
        description=(
            "Human-readable name. Not an identity: the agent's stable identifier is "
            "generated by the server, and renaming the agent does not change it."
        ),
        examples=["Support Triage"],
    )
    category: AgentCategory = Field(
        description="What kind of agent this is. Describes it; grants nothing.",
        examples=[AgentCategory.ASSISTANT.value],
    )
    version: str = Field(
        min_length=1,
        max_length=VERSION_MAX_LENGTH,
        description=(
            "The version being registered. A label, not a promise: ``1.2``, "
            "``2024-07-18`` and ``0.1.0-rc1`` are all valid."
        ),
        examples=["1.2.0"],
    )
    description: str | None = Field(
        default=None, max_length=DESCRIPTION_MAX_LENGTH, examples=["Answers tier-1 tickets."]
    )
    status: AssetStatus = Field(
        default=AssetStatus.DRAFT,
        description=(
            "Lifecycle state the agent starts in: ``draft`` or ``active``. A "
            "registration cannot start an agent suspended or retired — those are "
            "states an agent moves to, and the move is recorded as an update."
        ),
    )
    environment: Environment = Field(default=Environment.UNKNOWN)
    framework: str | None = Field(
        default=None,
        max_length=FRAMEWORK_MAX_LENGTH,
        description="The runtime or framework the agent is built on, if it is worth recording.",
        examples=["langgraph"],
    )
    build_revision: str | None = Field(
        default=None,
        max_length=BUILD_REVISION_MAX_LENGTH,
        description=(
            "Optional build identifier that distinguishes two builds of the same "
            "version. What it means is the organization's convention."
        ),
        examples=["a1b2c3d"],
    )
    identity_metadata: dict[str, Any] | None = Field(
        default=None,
        description=(
            "Runtime identity facts, validated against a closed model (``runtime``, "
            "``region``, ``instance``). Never credentials: a field that looks like a "
            "secret is refused."
        ),
        examples=[{"runtime": "python3.11", "region": "ap-south-1", "instance": "pod-7"}],
    )
    owner_user_id: uuid.UUID | None = Field(
        default=None,
        description=(
            "The member who owns this agent, by user id. Resolved against this "
            "organization's active memberships: a user who is not an active member "
            "here is refused, and a user from another tenant is not representable."
        ),
    )
    external_identifier: str | None = Field(
        default=None,
        max_length=EXTERNAL_IDENTIFIER_MAX_LENGTH,
        description=(
            "The identifier the producing system uses. When one is supplied, an "
            "existing ``agent`` asset with the same identifier is adopted rather "
            "than duplicated — and the request must agree with what is recorded "
            "there, or it is refused."
        ),
    )


class AgentUpdateRequest(BaseModel):
    """Request body for ``PATCH /organizations/{organization_id}/agents/{agent_id}``.

    Partial by construction: an absent field is left alone, a present field is
    applied, and the clearable fields may be set to ``null`` to remove the value.

    ``identity_id``, ``asset_id`` and ``organization_id`` are absent because they
    are not properties a client may change — an agent that has moved to another
    organization is a different registration, not an update. ``status`` moves the
    agent's lifecycle state and is validated against the transition rules in
    ``core/agents.py``; an impossible move is a 409, not a silent write.
    """

    model_config = ConfigDict(extra="forbid")

    display_name: str | None = Field(default=None, min_length=1, max_length=NAME_MAX_LENGTH)
    description: str | None = Field(default=None, max_length=DESCRIPTION_MAX_LENGTH)
    category: AgentCategory | None = None
    version: str | None = Field(default=None, min_length=1, max_length=VERSION_MAX_LENGTH)
    status: AssetStatus | None = None
    environment: Environment | None = None
    framework: str | None = Field(default=None, max_length=FRAMEWORK_MAX_LENGTH)
    build_revision: str | None = Field(default=None, max_length=BUILD_REVISION_MAX_LENGTH)
    identity_metadata: dict[str, Any] | None = None
    owner_user_id: uuid.UUID | None = None

    @model_validator(mode="after")
    def _check_shape(self) -> Self:
        """Refuse an empty patch, and refuse ``null`` where null means nothing."""
        provided = self.model_fields_set
        if not provided:
            raise ValueError("at least one field must be provided")
        for field_name in _REQUIRED_WHEN_PRESENT:
            if field_name in provided and getattr(self, field_name) is None:
                raise ValueError(f"{field_name} must not be null; omit it to leave it unchanged")
        return self

    def clears(self, field_name: str) -> bool:
        """Whether this request asked to remove ``field_name``'s value."""
        return field_name in self.model_fields_set and getattr(self, field_name) is None


class AgentRead(BaseModel):
    """A registered agent as returned by the API.

    The registry fields and the inventory fields are presented as one record,
    because that is what an agent is; they are stored in two tables so that the
    registry does not keep a second copy of the identity the inventory already
    enforces. ``identity_id`` is the value later phases will refer to when they
    attribute something to an agent; ``display_name`` is what a human reads.
    """

    id: uuid.UUID = Field(description="Registry row id. Internal; use ``identity_id``.")
    organization_id: uuid.UUID
    identity_id: uuid.UUID = Field(
        description=(
            "Stable identifier of this agent, generated by the server. It never "
            "changes: not when the display name changes and not when the version does."
        )
    )
    asset_id: uuid.UUID = Field(
        description="The inventory record this identity belongs to. Exactly one per agent."
    )
    display_name: str = Field(description="Human-readable name. Can change; the identity cannot.")
    description: str | None
    category: AgentCategory = Field(description="What kind of agent this is. Grants nothing.")
    version: str = Field(description="The version most recently registered for this identity.")
    framework: str | None
    build_revision: str | None
    status: AssetStatus = Field(
        description=(
            "Registry lifecycle state. A record, not a runtime control: nothing in "
            "this build starts, stops or blocks an agent."
        )
    )
    environment: Environment
    identity_metadata: dict[str, Any] | None = Field(
        description="Runtime identity facts (runtime, region, instance). Never credentials."
    )
    owner: AgentOwnerRead | None
    created_at: datetime = Field(description="When the identity was registered.")
    updated_at: datetime


class AgentListResponse(BaseModel):
    """``GET /organizations/{organization_id}/agents``.

    ``total`` is present only when the caller asked for it (``?total=true``), like
    the inventory's list: a count is a second pass over the same predicate, and a
    client paging by offset rarely needs it. ``count`` always describes the page
    itself, so a full page is distinguishable from the last one.
    """

    organization_id: uuid.UUID
    items: list[AgentRead]
    limit: int
    offset: int
    count: int
    total: int | None = None
