"""The agent registry's vocabulary: what an agent is, and how it is allowed to change.

Phase 3 records an *inventory*: a row per AI-related thing an organization knows
about, whatever its type. Phase 4 adds an *identity*: a registered agent is one of
those `agent` assets with a stable identity of its own, a category, a version, and
a lifecycle that moves in defined steps.

This module holds the parts of that idea that are pure vocabulary and pure rules —
no database, no HTTP — so they can be read, unit-tested and reused by the
repository, the API layer and a future ingestion path without any of them owning
the definition:

- :class:`AgentCategory` — what kind of agent this is. A description, never a
  capability: nothing in this build grants anything because an agent says it is
  ``autonomous``.
- :data:`AGENT_TRANSITIONS` — the lifecycle, as a table of allowed moves, with
  :func:`validate_transition` as the single place that reads it.
- :class:`AgentIdentityMetadata` — the small, closed, secret-free shape of
  "where is this agent running", validated like every other metadata contract in
  this codebase.

**Identity is not the display name.** The registry's stable identifier
(``identity_id``) is generated by the database, never derived from a name, a
version or anything a client sends. Renaming an agent, or shipping version 1.3 of
it, leaves its identity untouched — that is the entire point of having one.

**Suspension is a record, not a control.** ``suspended`` says the organization
considers this agent out of service. No credential is revoked, no tool is blocked
and no request is intercepted: those are later phases with their own permissions,
and claiming them here would be a lie the schema cannot back up.
"""

from __future__ import annotations

import json
import re
from collections.abc import Mapping
from enum import StrEnum
from types import MappingProxyType
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator

from aicore_api.core.assets import AssetStatus

__all__ = [
    "AGENT_CATEGORY_LABELS",
    "AGENT_INITIAL_STATES",
    "AGENT_TRANSITIONS",
    "BUILD_REVISION_MAX_LENGTH",
    "FRAMEWORK_MAX_LENGTH",
    "IDENTITY_METADATA_MAX_BYTES",
    "VERSION_MAX_LENGTH",
    "AgentCategory",
    "AgentIdentityMetadata",
    "normalize_optional_text",
    "normalize_version",
    "validate_identity_metadata",
    "validate_initial_status",
    "validate_transition",
]


class AgentCategory(StrEnum):
    """What kind of agent this is.

    Classification, not authorization. The registry stores the answer so a person
    can find an agent again, and so a later phase can make a *separate* decision
    about it — but no permission, policy or runtime behaviour is derived from this
    value in this build.

    ``other`` exists on purpose: a closed vocabulary that cannot express "not one
    of these" forces a wrong answer, and a wrong category is worse for a registry
    than an honest ``other``.
    """

    ASSISTANT = "assistant"
    WORKFLOW = "workflow"
    AUTONOMOUS = "autonomous"
    CODING = "coding"
    CUSTOMER_SUPPORT = "customer_support"
    DATA = "data"
    SECURITY = "security"
    OTHER = "other"


AGENT_CATEGORY_LABELS: Mapping[AgentCategory, str] = MappingProxyType(
    {
        AgentCategory.ASSISTANT: "Conversational assistant",
        AgentCategory.WORKFLOW: "Orchestrated workflow",
        AgentCategory.AUTONOMOUS: "Autonomous agent",
        AgentCategory.CODING: "Software engineering agent",
        AgentCategory.CUSTOMER_SUPPORT: "Customer support agent",
        AgentCategory.DATA: "Data agent",
        AgentCategory.SECURITY: "Security agent",
        AgentCategory.OTHER: "Not otherwise classified",
    }
)

#: States a *new* registered agent may start in. A brand-new record cannot be
#: created ``suspended`` (nothing has run yet to suspend) or ``retired`` (nothing
#: has ended yet), so those are refused rather than silently accepted.
AGENT_INITIAL_STATES: frozenset[AssetStatus] = frozenset({AssetStatus.DRAFT, AssetStatus.ACTIVE})

#: The lifecycle, as the complete set of moves. Anything not listed here is
#: refused: ``retired`` is terminal, so an agent that was withdrawn cannot quietly
#: reappear as active — bringing one back is a new registration with its own
#: record, which is what makes "this agent was retired" mean something later.
AGENT_TRANSITIONS: Mapping[AssetStatus, frozenset[AssetStatus]] = MappingProxyType(
    {
        AssetStatus.DRAFT: frozenset({AssetStatus.ACTIVE, AssetStatus.RETIRED}),
        AssetStatus.ACTIVE: frozenset({AssetStatus.SUSPENDED, AssetStatus.RETIRED}),
        AssetStatus.SUSPENDED: frozenset({AssetStatus.ACTIVE, AssetStatus.RETIRED}),
        AssetStatus.RETIRED: frozenset(),
    }
)

#: Bounded, printable fields. A version is a label a fleet is identified by, so it
#: is stored exactly as sent — trimming surrounding whitespace, refusing the empty
#: string and refusing control characters, but never guessing at a format.
VERSION_MAX_LENGTH = 64
BUILD_REVISION_MAX_LENGTH = 128
FRAMEWORK_MAX_LENGTH = 64

#: Identity metadata is a handful of facts about *where* an agent runs, not a
#: document store. The cap keeps it that way.
IDENTITY_METADATA_MAX_BYTES = 2 * 1024

_TEXT_PATTERN = re.compile(r"^[^\x00-\x1f\x7f]+$")

#: Key names an identity record must never carry, checked even though the model
#: already refuses unknown keys: this is the assertion that survives somebody
#: adding a field called ``api_key`` to the model in a later phase. Identity
#: metadata is safe to read through the API, and that has to stay true by
#: construction rather than by memory.
_FORBIDDEN_KEY_PARTS = (
    "secret",
    "token",
    "password",
    "passwd",
    "credential",
    "apikey",
    "api_key",
    "private_key",
    "authorization",
    "bearer",
    "signature",
)


def _require_printable(value: str, *, field_name: str, max_length: int) -> str:
    """Trim ``value`` and refuse it unless it is a printable label of that length."""
    normalized = value.strip()
    if not normalized:
        raise ValueError(f"{field_name} must not be blank")
    if len(normalized) > max_length:
        raise ValueError(f"{field_name} must be at most {max_length} characters")
    if not _TEXT_PATTERN.match(normalized):
        raise ValueError(f"{field_name} must not contain control characters")
    return normalized


def normalize_version(value: str) -> str:
    """Normalize the version label, or raise :class:`ValueError` describing why not.

    Deliberately not semantic-version-validated: a registry that rejected
    ``2024-07-18`` because it is not ``x.y.z`` would be rejecting real versions,
    and the registry's job is to record what the organization ships, not to have
    an opinion about how it numbers it.
    """
    if not isinstance(value, str):
        raise ValueError("version must be a string")
    return _require_printable(value, field_name="version", max_length=VERSION_MAX_LENGTH)


def normalize_optional_text(value: str | None, *, field_name: str, max_length: int) -> str | None:
    """Normalize an optional, nullable label (``framework``, ``build_revision``)."""
    if value is None:
        return None
    return _require_printable(value, field_name=field_name, max_length=max_length)


def validate_initial_status(status: AssetStatus | str) -> AssetStatus:
    """Refuse a starting state a new agent cannot have."""
    resolved = AssetStatus(status)
    if resolved not in AGENT_INITIAL_STATES:
        allowed = ", ".join(sorted(state.value for state in AGENT_INITIAL_STATES))
        raise ValueError(f"a new agent cannot start {resolved.value}: choose one of {allowed}")
    return resolved


def validate_transition(current: AssetStatus | str, requested: AssetStatus | str) -> None:
    """Refuse a lifecycle move that is not in :data:`AGENT_TRANSITIONS`.

    A no-op (a transition to the state the agent is already in) is allowed: an
    update that repeats a value is not a lifecycle change, and refusing it would
    make an idempotent PATCH fail.
    """
    from_state = AssetStatus(current)
    to_state = AssetStatus(requested)
    if from_state == to_state:
        return
    allowed = AGENT_TRANSITIONS[from_state]
    if to_state not in allowed:
        if not allowed:
            raise ValueError(
                f"{from_state.value} is a terminal state: an agent cannot move to "
                f"{to_state.value} once it has been retired"
            )
        rendered = ", ".join(sorted(state.value for state in allowed))
        raise ValueError(
            f"cannot move an agent from {from_state.value} to {to_state.value}; "
            f"allowed from {from_state.value}: {rendered}"
        )


class AgentIdentityMetadata(BaseModel):
    """Where an agent runs — a closed shape, and one that cannot carry a secret.

    Every field is optional and every field is a short label. There is deliberately
    no free-form ``extra`` escape hatch (``extra="forbid"``): an identity record a
    future phase reads to decide *which* agent is calling must not be a place where
    somebody parked a credential or an unvalidated blob.
    """

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    runtime: str | None = Field(
        default=None,
        max_length=64,
        description="Runtime the agent executes on, e.g. python3.11, node20.",
        examples=["python3.11"],
    )
    region: str | None = Field(
        default=None,
        max_length=64,
        description="Deployment region or cluster label.",
        examples=["eu-central-1"],
    )
    instance: str | None = Field(
        default=None,
        max_length=128,
        description="Instance, pod or host label the agent was registered from.",
        examples=["agent-runner-7c9f"],
    )

    @field_validator("runtime", "region", "instance", mode="after")
    @classmethod
    def _reject_unprintable(cls, value: str | None) -> str | None:
        """Refuse blank labels and control characters; trim the rest."""
        if value is None:
            return None
        if not value:
            raise ValueError("must not be blank")
        if not _TEXT_PATTERN.match(value):
            raise ValueError("must not contain control characters")
        return value


def validate_identity_metadata(
    payload: Mapping[str, Any] | None,
) -> dict[str, Any] | None:
    """Validate and normalize an identity metadata object.

    Returns the value to store — ``None`` when nothing was supplied, or when every
    field was ``None`` — and raises :class:`ValueError` describing the first
    problem, which callers translate into a 422.
    """
    if payload is None:
        return None
    if not isinstance(payload, Mapping):
        raise ValueError("identity metadata must be an object")

    for key in payload:
        if any(part in str(key).lower() for part in _FORBIDDEN_KEY_PARTS):
            raise ValueError(
                f"identity metadata must not carry credentials: {key!r} looks like one"
            )

    try:
        validated = AgentIdentityMetadata.model_validate(dict(payload))
    except Exception as exc:  # pydantic ValidationError; the message is safe to pass on
        raise ValueError(f"invalid identity metadata: {exc}") from exc

    stored = validated.model_dump(exclude_none=True)
    if not stored:
        return None
    encoded = json.dumps(stored, separators=(",", ":"), sort_keys=True)
    if len(encoded.encode("utf-8")) > IDENTITY_METADATA_MAX_BYTES:
        raise ValueError(
            f"identity metadata must be at most {IDENTITY_METADATA_MAX_BYTES} bytes when serialized"
        )
    return stored
