#!/usr/bin/env bash
# Run Alembic against the configured database.
#
#   bash scripts/migrate.sh upgrade head          # apply migrations
#   bash scripts/migrate.sh downgrade -1          # step back one revision
#   bash scripts/migrate.sh current               # show the applied revision
#   bash scripts/migrate.sh check                 # fail if models and schema differ
#   bash scripts/migrate.sh revision --autogenerate -m "add x"   # author a revision
#
# Credentials come from AICORE_DATABASE_URL (or .env) — never from alembic.ini.
# Review autogenerated revisions: they are code, not output.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

if [ ! -x apps/api/.venv/bin/python ]; then
  bash "$ROOT/scripts/py.sh" -c "pass"
fi

if ! apps/api/.venv/bin/python -c "import alembic" >/dev/null 2>&1; then
  echo "[migrate] installing API dev extras (alembic)" >&2
  apps/api/.venv/bin/python -m pip install --quiet -e "$ROOT/apps/api[dev]"
fi

exec env PYTHONPATH="$ROOT/apps/api/src${PYTHONPATH:+:$PYTHONPATH}" \
  apps/api/.venv/bin/python -m alembic -c "$ROOT/alembic.ini" "$@"
